# Estonian deliberative space {.chapter4 .chapter4_section}
 <script>
  window.location = "introduction-4.html";
  </script>

## Introduction {-.chapter_section .chapter4_section .intro_section #introduction-4}
<h1>Estonian deliberative space</h1>

```{block, type='authors authors_eng'}
<div class="author-links">**[Indrek Ibrus](#indrek-ibrus)**</div>
<div><a class="print-btn" href="../sissejuhatus-4.html">EE</a></div>
```

```{block, type='points'}
* The editorially unsupervised Estonian deliberative space is affective.

The affective, or extremely emotional, jargon being used on social media platforms, and in other web-based environments – the rapid labelling of news-based situations, the expression of worry or irritation, disparaging attitudes based on prejudices, and often hate speech – have started to impact public discussions. Since affective communication does not allow for social dialogue based on understanding, and relies on the spread of false information, media education for the broad population is needed to counter this.

* Discussions that require evidence-based expertise may be frustrating for scientists and experts.

The Estonian press is research-friendly and often provides a forum for scientists and other experts. However, complicated discussions requiring proof, which attract greater public attention, often result in ideological attacks on the experts themselves, and the negation of their expertise. At times, cartoonish treatments of academic discussion can be found in the press. Therefore, the press should find new ways of providing evidence-based discussions in a more balanced way.

* Estonian youth avoid public discussions.

Young Estonian internet users rely more heavily on social media than journalism to access news, but they consider the latter to be a more trustworthy news source. Young people do not participate very much in online discussion forums, since they reject the hierarchies and affective jargon found there. Instead of intermediated deliberative spaces, they prefer face-to-face conversations and tend to contribute to society through concrete real-life activities. Media leaders highly value young people’s media literacy.
```

### Points of departure {- .chapter4_section #points-of-departure-4}

The metaphoric concept of space is generally problematic. ‘Space’ is a handy term when one wants to speak about participants in complex relationships and their interrelated activities. ‘Cultural space’, ‘cyberspace’, ‘linguistic space’, ‘economic space’, ‘legal space’, etc. – these concepts simultaneously characterise a kind of inner unity, as well as an assumption of diversity. These spaces are usually limited; what is important is how they are differentiated from the other, different kinds of space. Often, the question that is left unanswered is how these figurative spaces relate to the real space – where people as physical objects spend most of their time. This issue is also relevant to this discussion. While the other chapters of the human development report provide various viewpoints on how spatial relations and organisation impact the well-being of society and democracy, here the discussion revolves around how the relations developing in the imagined space created by the discussions of the Estonian population impact human development and democracy in Estonia, as well as what is occurring in the ‘real space’.

Therefore, where is Estonia’s deliberative space, what is it comprised of, and who is creating it? The Estonian deliberative space is being created by the entire Estonian population, as well as the people who think and speak about Estonia around the world. A specific characteristic of the digital age is that a deliberative space can truly operate in step and relatively immediately around the world. However, at the same time, an internal thematic and ideological fragmentation has developed – Estonia is increasingly being spoken about differently in different semi-closed deliberative spaces. This contradiction is also reflected in the main tension in today’s deliberative spaces – on the one hand, a functioning democracy assumes the broad participation of society in discussions and for social agreements and consensus to be based thereon. On the other hand, a wealth of different views and unique ideas is also needed for society to have a broad choice of ideas and knowledge to choose from in order for progress to occur. However, in order to develop and mature, alternative ideas need somewhat differentiated and independent communication spaces.

```{block, type='blockquote-left'}
The function of the public deliberative space in a democratic society is to produce both the diversity and circulation of ideas, and simultaneously also select the best ideas and directions for development.
```

The function of the public deliberative space in a democratic society, the public good that the society provides, is comprised of a partially paradoxical contradiction; that is, it should simultaneously produce both the diversity and circulation of ideas, and should also filter out the best ideas (or those that provide an opportunity to arrive at a consensus) and development trends. The following chapter examines this topic from four angles: how do the various sub-spaces of this deliberative space operate; who participates in them; to what extent do they facilitate the introduction of new ideas and expert knowledge into the deliberative space; and to what degree do the discussions in the various sub-spaces promote dialogue and the development of common ground or agreement on the best possible solution.

The Estonian public deliberative space is created by various media. These include both the classical print and broadcast media, as well as the relatively new online versions of journalistic publications, social media platforms, the news and discussion environments of opinionated media or interest groups (e.g. the web environments of extreme right-wingers, investors or advocates of alternative therapies). All these media and their sub-environments have their own internal organisational principles, which determine who gets to speak, as well as when and to what extent. The rules established by journalistic institutions are the most considered and most adhered to. However, with the dynamic development of the internet, the rules in the journalistic environments have been continually changing in the last few decades. Media market concentration, and the related consolidation of various types of media within media groups, has also played a role.

```{block, type='blockquote-right'}
The development of the deliberative space depends on the balance between two opposite trends – convergence and fragmentation – in the media.
```

The fact that large enterprises are more efficient, and therefore more powerful, has always characterised media markets, and this has always resulted in oligopolistic markets that are controlled by a few large media concerns. During the age of online media, this trend has intensified. The four largest so-called ‘media houses’ (Estonian Public Broadcasting, Postimees Group, Ekspress Group and Äripäev) organise the deliberative spaces created by Estonia’s mainstream or journalistic media channels. The media houses also try to achieve efficiency through economies of scale by cross-using and cross-marketing their channels and publications. In the course of this activity, many past rules related to journalistic ethics and the organisation of the deliberative space have had to be reviewed. Specific changes have been caused by the comments sections of the publications, which are less controlled, as well as the activities of the media institutions in social media. This has resulted in the reduction of editorial control over the deliberative space. The internal consolidation of the media groups has also helped to neutralise the fragmentation of Estonian deliberative spaces based on the type of media. For instance, the web portals of these companies (Postimees.ee and Delfi.ee) aggregate almost all the content produced by their publications and channels. Therefore, a counterforce (i.e. convergence) also exists and the development of the deliberative space depends on the balance between these two opposite trends.

### Articles in this chapter {- .chapter4_section #articles-in-this-chapter-4}

Below, I will summarise and link the key messages of the articles in this chapter – the results produced by Estonian media and communications researchers during the last few years. I will separately consider the two main types of media – editorially supervised journalistic media and social media outlets that are not editorially supervised.

Participation in online media, including social media that is not editorially supervised, is analysed in this chapter by Andreas Ventsel and Mari-Liis Madisson in their article about social-political communication in social media, and Veronika Kalmus and Andra Siibak in their article about the participation of Estonian youth in the virtual deliberative space. Both articles allude to the communication risks in online media. During the early days of the internet, a significant democratising power was attributed to it, and social media (primarily Facebook, where users appear under their full names) was seen as powering rational democratic debate. However, during the past few years, researchers of internet communications in both Estonia and the rest of the world have instead alluded to problems. Ventsel and Madisson demonstrate that a movement toward the simplification of argumentation has occurred in the discussions of public issues online, and that easily grasped messages with a strong emotional charge dominate.

```{block, type='blockquote-left'}
The function of affective communication is the initial labelling of current social developments, in order to express the significance of certain aspects in the interpretation of events and phenomena.
```
As a significant contemporary author, Zizi Papacharissi ([2016](#Papacharissi2016)) has introduced the concept of affective communication. This refers to occasions when short and immediate posts create a cognitive atmosphere that shapes certain topical themes and a shared sense of urgency. The function of affective communication is the initial labelling of current social developments, in order to express the significance of certain aspects in the interpretation of events and phenomena. This shared experience is important in times of crisis, when social media can be used to demonstrate collective concern or irritation, and the expression of initial positions. In both crisis situations, as well as at other times, the ability of social media to express emotions that would otherwise be suppressed is associated with affective communication. Disparaging statements, prejudices or even hate speech are also more likely to occur ([Tiidenberg 2017](#Tiidenberg2017), p. 58). By hate speech we mean expressions of opinion that threaten, insult or humiliate people and are not based on their personal characteristics but on their membership in a group; for example, membership in a racial, ethnic, religious, disability or sexual orientation group.

The distinctive feature of social media and other online forums is that they have allowed for a significant diversification of public deliberative spaces. These environments can be linked to the deliberative space created by journalism, where topics are mediated by ordinary opinion leaders (journalists, politicians, scientists, experts). But they can also operate completely separately if they focus on people who have been ignored in the press or those who have become influencers through social media (e.g. YouTubers, Instagram celebrities, Twitter or Facebook micro-bloggers, etc.), who have been able to attract followers with their unique content and style. However, the relatively closed nature of alternative discussion environments has been seen as a risk – not only does a limited circle of people participate in the discussions, but the subjects of the discussions, their ideological basis and sources of information are one-dimensional. These environments consolidate existing understandings and values, and most reinforce the already established world views of the participants. Information that diverges from already formed opinions is often viewed as suspicious and not taken seriously. This attitude is called the echo chamber effect. If there is a proliferation of such spaces, it will lead to a broader internal polarisation of society ([Madisson and Ventsel 2016](#Madisson2016)).

```{block, type='blockquote-right'}
Only a very small part of society (4% to 5% according to various studies) limits its media consumption and information searches to a few environments.
```

During recent years, foreign researchers (e.g. [Dutton et al. 2017](#Dutton2017)) have shown that the echo chamber effect is not as great in society as had been feared. Only a very small part of society (4% to 5% according to various studies) limits its media consumption and information searches to a few environments. Most people in their daily lives come into contact with quite a diverse spectrum of media content. And most internet users are now skilfully using search engines that provide people with different kinds of information. However, an indirect, but problematic, aspect of closed or semi-closed and affective deliberative spaces is their logic that promotes confrontation and polarisation. In this, not only do groups with different views become confrontational, but so too do media institutions and the discussion environments they create, as well as the institutionally recognised experts.

```{block, type='blockquote-left'}
Estonia lacks a mechanism that would directly motivate researchers to participate in public discussions.
```

In regard to editorially supervised media, the article by Ragne Kõuts-Klemm tells us that affective communication also prevails in the comments sections of online newspapers. Most comments address that which is irritating and polarising. Consequently, even these, mostly moderated environments, may become places where hate speech quickly escalates. At the same time, we learn from Kõuts-Klemm that the number of people who have the opportunity to express their opinions in the form of op-ed articles in newspapers or on their websites is quite limited – they are usually well-known people or those with experience in the opinion genre. The fact that experts and scientists often appear on op-ed pages should be seen as positive, and shows that the op-ed pages of Estonian newspapers are ‘research-friendly’. And yet, participation in the social debate can often be somewhat exasperating for the research community. In his article, Arko Olesk points out that Estonia lacks a mechanism that would directly motivate researchers to participate in public discussions. Most do so as active citizens. Both Olesk as well as Kõuts-Klemm show how, in cases where a more complicated and scientifically knowledgeable approach is required, the media may not be up to handling the topic, and sometimes focuses on the accompanying conflict rather than weighing the facts and arguments behind it. The media may ridicule the differences of opinions in the research community, and in the case of controversial topics, experts must often deal with attacks on their expertise, the ideological levelling of the discussion, and annulment of expert knowledge. Such experiences can be frustrating for experts and reduce their interest in participating in the deliberative space.

A significant related development, which is examined in the article by Veronika Kalmus and Andra Siibak, is the fact that the next generation – the youth – may be wary of the kind of deliberative space described above, which is either affective or hierarchical, as is often the case in media publications. Although news and social debates reach the youth mostly through social media and not the direct consumption of journalism, they still have more trust in journalistic media outlets as news sources. They are critical of the virtual deliberative space, and think it lacks a polite and reasoned communication culture. Therefore, instead of the virtual deliberative space, they prefer face-to-face communications and a direct, hands-on approach to dealing with social issues.

```{block, type='blockquote-right'}
Publications that have remained independent need to search for secondary activities to help them survive and this has often increased their dependence on local authorities.
```

However, one of the greatest problems of editorially supervised media, which also impacts Estonia’s spatial development, is the complicated situation related to county and local journalism. This was dealt with in a study conducted by Tartu and Tallinn media researchers in early 2019 ([Kõuts-Klemm et al. 2019](#Kõuts-Klemm2019)). One of the existing sources of income is advertising, although the advertising income of Estonian media companies is increasingly limited due to the advertising brokerage activities of international digital platforms. In addition, since most economic activity is concentrated in the large cities, the advertising markets in the counties and rural municipalities has decreased to the point where the survival of high-quality local journalism is at risk. A large number of the county newspapers have already been bought by Estonia’s larger media companies, and as the result of economies of scale within the group, the reach of local publications has often declined. Publications that have remained independent need to search for secondary activities to help them survive and this has often increased their dependence on local authorities. Fearful of losing their cooperation partners (e.g. local governments, advertisers), the local press may not fulfil their critically important task of monitoring the exercise of economic and political power. Local governments that fund their own free publications often sell advertising in them, thereby making it more difficult for local independent media to survive. All this threatens the functioning of the local deliberative space. If there are no independent institutions that drive and promote local debate, it reduces the possibility that local development goals can be established by consensus and that effective local information exchange will be able create new opportunities in the daily lives of people and businesses in less populated areas.

### How do we move forward? {- .chapter4_section #how-do-we-move-forward-4}

The foregoing may be summed up as follows: Estonia’s mediated deliberative space does not operate ideally. If the problems created in the deliberative space by the journalistic media – focus on conflicts, simplification of phenomena, giving a voice to well-known people with generic approaches – are old, then what is new in regard to online media is a partial fragmentation and a sometimes striking unwillingness to engage in social dialogue, a refusal to acknowledge expertise-based authority, and the general spread of affective speech. This, in turn, has resulted in the reluctance of some social groups, including young people, to join the public social debate. These problems are not unique to Estonia. These trends are being observed in many places around the world, all the more because the communication platforms are generally the same. To the extent that major social media platforms are being held responsible for the risks to democracy posed by online environments, the European Union and other large countries have started to demand that these platforms stop the spread of fake news and are closing down environments where hate speech or misinformation is regularly spread. Considering the fact that the functioning of the Estonian deliberative space and the quality of social dialogue depends on international platforms, Estonia must participate attentively and insistently in the work of the European Union as a capable regulator of international markets in this field.

```{block, type='blockquote-left'}
Local Estonian media organisations have been losing market share (and advertising money) to global platforms.
```

In regard to international regulatory work, as well as the development of Estonia’s media policy, it should be remembered that local Estonian media organisations have been losing market share (and advertising money) to global platforms. It is important to direct some of this money back into these platforms by, for instance, taxing the global platforms in order to empower the local press in shaping Estonia’s deliberative space. Special attention needs to be paid to the county and local press, which is most vulnerable. And since its work directly influences the quality of the public deliberative space outside the larger cities, they also impact Estonia’s balanced spatial development. However, Estonia’s county and local press cannot be empowered by grants or subsidies alone. Instead, broader cooperation must be developed between Estonia’s media and cultural institutions and the public sector. An important trend is the sharing of data, especially open data, as are the endeavours to more directly amplify each other’s actions. Among other things, the support of Estonian Public Broadcasting for the local press and the deliberative space in less populated areas must be significantly improved. For example, the network of correspondents should be expanded, in order to ensure a greater presence, especially in south Estonia, and to provide local publications and channels with services and platforms for developing online environments.

```{block, type='blockquote-right'}
Special attention needs to be paid to the county and local press, which is most vulnerable.
```

In order to develop a broader deliberative space in Estonia, it is critically important to involve various types of expertise in the public discussion. The Estonian press does provide a platform for scientists and other experts but at the same time the treatment of topics may not be balanced. Media channels must find ways of presenting topics requiring complex proof to the public in a way that reduces the emotional nature of the discussion and produces more of a dialogue that focuses on seeking understanding and finding solutions. The people directing research institutions and research policy must also find better ways of motivating academics to participate in public discussions, and training them to do so with impact, thereby increasing general awareness and promoting discussion.

As stated at the beginning of this introduction, the broader deliberative space must on the one hand enable diverse, alternative ideas to emerge and mature, but on the other hand also seek general social dialogue and consensus. From the perspective of the press as the shaper of the deliberative space, this means the creation of, or search for, more specific thematic deliberative spaces (e.g. forums of specific research fields). Secondly, dialogue between these spaces should be enabled, along with the communication of important ideas and knowledge to the general public, also involving the citizenry through discussions based on moderated means of recruitment. Based on the theory of national innovation systems ([Lundvall 2010](#Lundvall2010)), this connection of various knowledge spaces is the main prerequisite for the development of a dynamic deliberative space that is able to constantly synthesise new ideas and various alternative ways in order to either manage risks or realise new development opportunities. If usually, the importance of good cooperation between universities, business and the public sector is stressed as being necessary for the development of such a national innovation system, then in today’s online era, the importance of high-quality journalism and media, as the curator of a broader social exchange of ideas must also be recognised ([Ibrus 2019](#Ibrus2019)).

```{block, type='blockquote-left'}
Avoiding the risks of web-based communication undoubtedly depends on how the general awareness of these risks increases.
```

The development of a discussion culture, and especially avoiding the risks of web-based communication, undoubtedly depends on how the general awareness of these risks increases. Interviews with Estonian media leaders indicated ([Kõuts-Klemm et al. 2019](#Kõuts-Klemm2019)), that today’s youth is actually more critical of the media and sources than the older generation. The caution of younger people is also revealed in Kalmus and Siibak’s article in this anthology. One of the objectives could be to expand the media education programmes in schools in order to reach more of the general population. Such programmes could be headed up by the media organisations themselves as parties that are critically interested in the quality of the deliberative culture.

### References {-.subreferences #references-4}

<p id="Dutton2017">Dutton, W. H., Reisdorf, B., Dubois, E., Blank, G. 2017. Social shaping of the politics of internet search and networking: moving beyond filter bubbles, echo chambers, and fake news. Quello Center Working Paper No 2944191. Lansing: Michigan State University.</p>

<p id="Ibrus2019">Ibrus, I. (ed.) 2019. Emergence of Cross-innovation Systems: Audiovisual Industries Co-innovating with Education, Health Care and Tourism. Bingley: Emerald.</p>

<p id="Kõuts-Klemm2019">Kõuts-Klemm, R., Harro-Loit, H., Ibrus, I., Ivask, S., Juurik, M., Jõesaar, A., Järvekülg, M., Kauber, S., Koorberg, V., Lassur, S., Loit, U., Tafel-Viia, K. 2019. Meediapoliitika olukorra ja arengusuundade uuring. Tartu, Tallinn: Tartu Ülikool, Tallinna Ülikool.</p>

<p id="Lundvall2010">Lundvall, B. Å. 2010. National Systems of Innovation: Toward a Theory of Innovation and Interactive Learning. London: Anthem Press.</p>

<p id="Madisson2016">Madisson, M., Ventsel, A. 2016. Autocommunicative meaning-making in online-communication of Estonian extreme right. – Sign Systems Studies, 44 (3), 326−354.</p>

<p id="Papacharissi2016">Papacharissi, Z. 2016. Affective publics and structures of storytelling: sentiment, events and mediality – Information, Communication & Society, 19 (3), 307–324.</p>

<p id="Tiidenberg2017">Tiidenberg, K. 2017. Ihu ja hingega internetis. Tallinn: Tallinna Ülikooli Kirjastus.</p>
