## Socio-political discussion in the digital public space {.chapter_section .chapter4_section}

```{block, type='authors authors_eng'}
<div class="author-links">**[Andreas Ventsel](#andreas-ventsel) and [Mari-Liis Madisson](#mari-liis-madisson)**</div>
<div><a class="print-btn" href="../ühiskondlik-poliitiline-diskussioon-digitaalses-avalikus-ruumis.html">EE</a></div>
```

```{block, type='points'}
* Clear principles of journalistic ethics and quality do not apply to the messages published in the public space of social media as they do in the case of professional journalism.
```

In Estonia, electronic devices became the channels used by the majority of those actively following the media in 2011. This article focuses on the trends in meaning creation that characterise social media communications and their role in shaping the socio-political discussion.

```{block, type='blockquote-right'}
Meaning creation is a process through which communication partners seek to understand each other and the world around them and to influence and, in some cases, even mislead their discussion partners.
```

Our objective is to show which meaning creation leads to the closure and radicalisation of social media, and which leads to more democratic open communication. We refer to specific examples and studies that can help map the features of social media debates and the types of meaning creation. Few qualitative studies have been published in Estonia on the specifics of (social) media meaning creation. It is also important to understand that the digital public space is much broader than just social media, although very different channels and information spheres converge in social media and it is one of the main places where citizens participate in the discussion of public topics. An information environment has evolved – this is a digital public space where users of interactive devices connected to the network can consume information created by others and participate in creating information. Academic literature has also pointed out the problems related to the emergence of the information environment. One such problem is the fact that there has been a strong shift towards simplification and personalisation when discussing public issues in the digital media.

```{block, type='blockquote-left'}
The digital public space is much broader than just social media, although very different channels and information spheres converge in social media and it is one of the main places where citizens participate in the discussion of public topics.
```

Traditionally, socio-political debates have reached wider audiences through the press, where the editorial staff select speakers from diverse backgrounds, as well as strive to ensure that the discussions stay on topic and are debated according to the rules. In the social media era, the number of public deliberative spaces has significantly diversified, and speakers no longer need to depend on the mediating role of the press to reach the largest possible audiences. In social media, so-called traditional opinion leaders (journalists, politicians, academics, experts) can mediate public topics as can the accounts of various enterprises and institutions, discussion groups, as well as social media influencers (such as YouTubers, Instagram celebrities, Twitter or Facebook micro-bloggers, etc.), who, through frequent posts, interesting content, and engaging styles, have been able to attract a large following. Social media mediators gather information on specific topics and often provide guidelines for interpreting that information; in addition, their pages provide an opportunity to discuss the posted content with both the intermediaries themselves and their audience. Studies have shown that younger audiences, in particular, prefer social media as their main channel for keeping up with public topics, and do not consider texts produced by journalism to be the main and preferred news medium ([Vihalemm and Kõuts-Klemm 2017](#Vihalemm2017), pp. 256, 258; [Opermann 2018](#Opermann2018)). The main risk with social media mediators is that they have a great deal of power over the development of the social significance of certain topics, but their goals and policies often remain hidden from their audiences.

```{block, type='blockquote-right'}
There has been a strong shift towards simplification and personalisation when discussing public issues in the digital media.
```
Research by Saara Jantunen ([2018](#Jantunen2018)) and Thomas Elkjer Nissen ([2015](#Nissen2015)) has shown that Russian Information War warriors seeking to sow misleading links, fuel conflict and undermine NATO’s credibility are particularly dangerous when they succeed in becoming popular mediators or social media influencers. Their main goal is to shape public opinion in ways that allow the organisers of the information attacks to achieve their political and economic goals. Such subversive actions use highly emotional and/or controversial themes, combine them with events familiar to the target audience and strategically designed stories. For example, fake characters (sometimes played by actors) are used to make the false information seem more trustworthy, along with artificially generated social media activity (paid likes and comments), non-existent scientific sources, conspiracy theories and contradictions that fuel conflict.

### The affordances of social media encourage emotion-based communication {-.chapter4_section}

Understanding the technical and social capabilities of social media platforms is important when dealing with the specificities of the social media deliberative space. According to Katrin Tiidenberg ([2017](#2Tiidenberg2017), p. 21), due to the affordances (opportunities) provided by social media, certain types of behaviour and usage is more convenient for the users, and therefore more likely to occur than others. For instance, permanency, the automatic storage and archiving of what is displayed on social media, copy-ability, or the ease of copying texts, and searchability, or inclusion of content in search engines ([ibid.](#2Tiidenberg2017), p. 67) have all been mentioned as the most significant affordances of social media. In addition, a sense of anonymity or invisibility has been mentioned as one facet of the affordance of social media that encourages people to share insights frankly. Thus, emotions, which would otherwise be repressed, are often expressed on social media, and in this context, disparaging statements, prejudices or even hate speech are more likely to occur ([ibid.](#2Tiidenberg2017), p. 58).

```{block, type='blockquote-left'}
Social media affordances encourage the emergence of public communities characterised by their speed of formation, geographical dispersion, anonymity and emotion.
```
The popularity of reactions, as well as the copying and sharing functions have been associated with making the social media deliberative space more emotion-based and less argument-based. Due to tolerance, the amplification of the feeling of being connected, involved and experiencing texts together plays a role with unprecedented importance in social media discussions. Communication researcher Zizi Papacharissi ([2016](#2Papacharissi2016)) and her team examined millions of tweets sent out during the Occupy Wall Street actions and the Arab Spring (especially in Egypt) and adopted the phrase affective storytelling to describe this type of communication. One of Papacharissi’s ([ibid.](#2Papacharissi2016), p. 311) most important conclusions was that quick reactions, or affective social media threads, generally comprised of rather short posts, can create a cognitive atmosphere that shapes certain topics and a common perception of the urgency and importance of these topics but is also a rudimentary way of initially labelling their collective meaning. Such affective communication is based on the common recognition that certain aspects are important to give events or phenomena meaning, although they are not yet structured into distinct units of meaning. An affective sense of experiencing something together is especially likely to occur in social media during times of crisis, disaster and conflict; that is, when social media is used to express collective concern and irritation.

### Internet use in Estonia {-.chapter4_section}

According to the study *Me. World. Media* (*Mina. Maailm. Meedia* / *MeeMa*), internet use has increased at a very fast pace since the late 1990s, and especially since the turn of the century. According to the Kantar Emor data used in the study, internet usage among people aged 15 to 74 has increased from 28% in 2000 to 83% in 2014 ([Vihalemm and Kõuts-Klemm 2017](#Vihalemm2017), p. 263). Estonian indicators are comparable to those of the US and Great Britain, where 87% of the adult population use the internet ([ibid.](#Vihalemm2017), p. 252). As confirmed by the Emor and MeeMa studies of 2014, the internet has not only become the most popular medium among the youth, but has similarly impacted the consumption of traditional media among other age groups ([ibid.](#Vihalemm2017), p. 264). However, the differences in internet usage based on education or gender are smaller than those based on age – 100% of the younger age group (15–19 yrs) are internet users, 75% of the middle-age group (40–49 yrs) and 54% of pensioners. There are also no significant differences between Estonian-speaking or Russian-speaking people ([ibid.](#Vihalemm2017), p. 264).

Social media experienced explosive growth at the end of the first decade of the new century and it became the centre of both the public and private information space. According to the study commissioned by the Ministry of Culture ([Kaldur et al. 2017](#Kaldur2017)), the Facebook platform is popular among both Estonian- and Russian-speaking populations, with 56% of all Estonians (and even 90% of the youth) using it actively and 43% of the Russian population also doing so. In addition to Facebook, the Russian-language platforms Odnoklassniki (33%) and VKontakte (26%) are also popular among the Russian-speaking population. Estonian people are used to sharing information, news and monitoring, as well as sometimes participating in, the political debate on their portable interactive screens. While we can see that interest in the news continues to be strong among the population, and it is only the channels used to follow it that have changed, to the detriment of ‘traditional’ media channels. Roughly a quarter of the respondents to the 2014 MeeMa survey said that they have stopped reading newspapers due to the internet, and 10% said they had stopped following the TV and radio news in the traditional way ([Vihalemm and Kõuts-Klemm 2017](#Vihalemm2017), p. 254). According to the MeeMa study, a user type has emerged whose media repertoire is limited primarily to social media and spends very little time on internet portals or websites.

*Apparently, interest in communication and entertainment predominates among the interests of this type, while there is little interest in news and discussion platforms. It can be said that a significant change in the media preferences of the population has occurred between the first [2004] and last Mina. Maailm. Meedia surveys [2017]: almost 50% of Estonians prefer the internet for media usage. This in turn means an even more extensive fragmentation of the auditorium.* ([Vihalemm and Kõuts-Klemm 2017](#Vihalemm2017), p. 274)

Numerous discussion platforms, public (various newspapers and groups available to registered users) and semi-public (groups that can be accessed with the approval of the administrator), have developed on the internet. Some of these are centred around a world view, (e.g. ‘Virginia Woolf Sind Ei Karda!’ [Virginia Woolf is not afraid of you], ‘EKRE Sõprade Klubi’ [Friends of the Conservative People’s Party of Estonia club]) while others discuss current social topics (e.g. ‘Aitäh, aga minu traditsiooniline perekond ei vaja kaitset’ [Thanks, but my traditional family does not need protecting], ‘Eesti Metsa Abiks’ [Estonian forest aid], ‘EI PAGULASMASSIDELE’ [Estonians against refugee quotas]). However, it is also true that weighing in on public topics (news about cohabitation, political debates, etc.) is not the main and only focus of digital media usage. People also use social media to communicate with their friends and acquaintances, and create and consume entertaining content.

### Closed meaning creation evokes polarisation {-.chapter4_section}


```{block, type='blockquote-right'}
Closed meaning creation is characterised by a disparaging and dismissive attitude towards opponents and other possible points of view.
```
The analysis of social media communication within the framework of open and closed meaning creation helps us understand the factors that can either lead to communication encapsulation or promote dialogue. We define communication as closed meaning creation if it primarily supports the connections that the potential receiver already knows, and tends to avoid alternative points of view ([Madisson and Ventsel 2016](#Madisson-Ventsel2016)). Getting stuck in stereotypes and exchanges of views that are too one-sided are seen as being the main problem with the discussion climate on social media. On social media, the preference is for information and communication spaces that reinforce existing understandings and values, or at least coincide with existing beliefs without creating discomfort or inconsistency. However, information that deviates from existing understandings is viewed as insignificant or not worth delving into. This attitude is called the echo chamber effect, which increases and synchronises community memory, and causes prejudices and common positions to become entrenched and polarised ([ibid.](#Madisson-Ventsel2016)) as similar conversation partners communicate.

```{block, type='blockquote-left'}
The echo chamber effect characterises a communicative situation in which prejudices and common positions become entrenched and polarised when communicating with very similar conversational partners.
```

The disparaging and cartoonish characterisation of one’s opponents is typical of the social media echo chamber, which in turn reduces the possibility of developing a dialogue. From the viewpoint of meaning creation, the result is highly predictable because it is based on antithetical logic that causes sharp opposition. This divides the world into two oppositional (binary) parts: the moral and the immoral, the useful and harmful, friends and enemies, etc. This echo chamber effect often appears in social media discussions that develop around conflicting issues related to ordinary life, be it a plan for setting up a wood processing plant, a forestry policy or migration framework (see [Olesk, this report](#the-role-and-status-of-experts-in-societal-media-discussions)). The echo chamber effect is felt especially strongly in communications among people with extreme political views. For example, a qualitative study of the blogs of Estonian right-wing extremists ([Madisson 2016](#2Madisson2016)) showed that the closed meaning creation that occurs often does not allow for a perception of the relativity of values and norms, and does not recognise the plurality of interpretations and points of view. This type of meaning creation was forcefully presented in the posts focused on the European migration crisis of 2015–2016. Consequently, ‘noble’, ‘just’, ‘balanced’, ‘indigenous’ Estonians who were not influenced by foreign propaganda were contrasted with groups that promote ‘deceitful’, ‘greedy’, ‘two-faced’, ‘unnatural’, ‘stupid’ and ‘hysterical’ rhetoric, as well as the ‘brainwashed’ masses of ordinary citizen corrupted by the media and education system ([ibid.](#2Madisson2016)). The study dealing with the public social media content of the Conservative People’s Party of Estonia and its leading figures in 2014–2016 also revealed a noteworthy share of antithetical meaning creation. For example, the party’s social media rhetoric positioned all possible opponents, for instance, the defenders of women’s and LGTB rights, representatives of the Russian-speaking population, leading politicians of the other political parties, Estonia’s large media outlets, and many social theorists (e.g. Herbert Marcuse and Theodor Adorno) as dangerous enemies ([Kasekamp et al. 2018](#Kasekamp2018)).

Social media communication is hybrid by nature because the public, private as well as alternative information spheres are often intertwined on platforms that serve commercial interests (e.g. Facebook and Twitter). And yet, the people who participate in social media groups tend to value their information spaces because these are perceived as having sprouted from the grassroots level or ‘from among the people themselves’. In the discussion groups that are characterised by polarisation and a strong echo chamber effect, a forceful confrontation with leading media outlets, and often with the authorities, is apparent. In these deliberative spaces, the authority of the grassroots level is stressed, which primarily means that unofficial knowledge – customs and understandings – are trusted and the impact of the institutional sphere (e.g. the government, media companies, educational institutions, etc.) in its creation and communication is imperceptible ([Howard 2011](#Howard2011), pp. 7–10). The perception of some knowledge and attitudes as having arisen from the grassroots level functions as a value criterion, in which trustworthiness is based less on the quality of the arguments and reasoning, and more on its opposition to the mainstream. This trend was alluded to in Andra Siibak and Anu Masso’s qualitative study (2018), which is based on interviews with the members of the anti-immigrant Facebook group ‘EI Pagulastele / Estonians against refugee quotas’, who discuss the reasons they actively visit this group. Mostly anti-elite attitudes emerged, including a deep distrust in the large media channels, and the political parties. The interviewees shared their position that the anti-refugee Facebook group is the only channel that provides non-biased information on immigration. The respondents valued personal stories, where ‘people like them’ described their own (generally negative) experiences with supposed immigrants ([ibid.](#Siibak2018), pp. 317–318). In their conclusions related to the study, the authors note ([ibid.](#Siibak2018), pp. 318–319), that the anti-refugee group also functioned as an echo chamber that amplified and unified the prejudice related to mass immigration.

```{block, type='casebox'}
<h3>Example of a closed communication group</h3>

Along with the echo chamber-like policy discussion groups, meaning creation opposed to institutional authority is also widespread in the discussions related to alternative medicine. The closed Facebook group called ‘MMS ja DMSO Eesti’, where the use of MMS or chlorine dioxide is promoted as a ‘a wonderful mineral solution’ for the prevention and cure of various diseases, has become a great topic of conversation among the Estonian public. This group collected almost 8,000 followers and forcefully opposed Estonia’s official medical system and the larger media publications. It also accused the latter of a malicious libel campaign and conspiracy. Due to public attention and an appeal by the Health Board, Facebook shut the group down in September of 2018.
```

A strong ability for community bonding can compensate for information usage based on stereotypes and repetitions resulting from echo chamber communications. The goal of communication is the recognition/non-recognition of one’s conversational partner, and an important role is played by the establishment of a trustworthy contact that is based on the confirmation of intra-group norms and creating a sense of uniformity. In addition, this type of communication most probably ensures the motivation for and sense of security in maintaining contacts, since the messages created in the ‘right’ way ensure positive feedback, which in turn provides the impetus for continued communication. At the same time, the communication directed at the creation of social relations may be available to only a limited audience; for example, recommendations from members of the social group may be required when joining the group or be regulated by forms resembling questionnaires. The eligibility of new members is usually decided by the trustees or moderators chosen by the social media group.

### Open meaning creation involves various parties {-.chapter4_section}

As the term suggests, open meaning creation is open to new communication partners and alternative viewpoints. Open meaning creation is directed at the synthesis of various positions and is ideally based on the terms of deliberative democracy, according to which communication should be:

1) free – only the results and rules of the discussion are binding;

2) reasonable – only the ‘force of the better argument’ applies ([Habermas 1998](#Habermas1998));

3) based on the principle of equality – everyone has an equal right to speak and criticise, and

4) consensual – the ideal discussion is focused on achieving rationally motivated consensus among the communication partners ([Cohen 1989](#Cohen1989)).


```{block, type='blockquote-right'}
Ideally, open meaning creation allows the participants in the discussion to arrive at a rationally motivated consensus.
```

Social dialogue means discussing public issues in a reasoned way that allows all the stakeholders to be involved on an equal basis. An important goal of the dialogue is to understand the communication partners, and develop a position that takes all the parties into consideration. As opposed to closed meaning creation, an important criterion of dialogue-based and open meaning creation is an attempt on the part of the communication partners to find a common language that makes it possible to discuss issues of social importance. This manifests itself, for example, if one conversational partner asks the other to clarify an incomprehensible term or if an attempt is made to agree on the rules on which to base the dialogue. The fact that communication participants provide different interpretations when talking about the same thing is natural. Open meaning creation is characterised by a constant clarification of the boundaries of the topic in question, and directing attention to the inconsistencies in the positions of the dialogue partners, which enables a mutually evolving understanding to be sought. Dialogue-based communication results in the considered and integrated development of various perspectives, world views and points of emphasis. Adhering to the requirements of open meaning creation enables the communication participants to formulate reasonable preferences and decisions.

Setting certain restrictions on social groups can help to support open meaning creation in social media in the public space. For example, these include establishing rules of procedure which respect the principles of dialogue, moderating the discussions and requiring personal identification. The latter helps to avoid a situation where false identities (e.g. trolls or pawns) are created in order to artificially boost the popularity or unpopularity of certain positions in order to manipulate the audience.

Moderating mainly involves removing inappropriate writings, approving or rejecting requests to join the group, and keeping the discussion focused. In the case of Estonia, there has been limited research on the connections between moderating and the quality of social media discussions. An analysis that focused on the moderating of a semi-public Facebook group ([Orgse 2018](#Orgse2018)) revealed the following problem: due to the established values of the moderators, they often had difficulty creating the ideal conditions for a dialogue; for example, giving voice to those whose positions differed fundamentally from their own. However, in high-membership groups, it is more difficult to secure the opinions, frankness and criticism of all users.

### Summary {-.chapter4_section #summary-41}

In this article, we have drawn attention to aspects of meaning creation which, when they dominate, promote the polarisation of social media discussions and prevent the development of reasoned discussion and the integration of various social groups. No means of communication can be considered as harmful in and of itself. For example, in times of serious social crisis, antithetical meaning creation can act as an effective mobiliser; likewise, the affirmation of social connections is important in almost every communication situation. They become problematic when the aforementioned features of meaning creation start to dominate the communication environment in ways that overshadow the formulation of dissenting opinions, inhibit the critical analysis of the communicators’ decision-making processes and increase the danger of manipulation.

```{block, type='blockquote-right'}
To enhance the overall quality of social media discussions, media education should be promoted, which teaches people how to critically analyse today’s information-saturated online communications.
```
The improvement of social media communication skills can be directly associated with the development of a psychological protection strategy by the Estonian population. In liberal democracies, antagonistic information activity can justify itself under the banner of freedom of expression. Unlike the professional press, social media mediators are exempt from the principles of ethics and quality that emphasise fact-checking, being source-based, the presentation of expert opinions, and the norms of neutral reporting and balanced views. This can result in an ‘information fog’ that is inherent to antagonistic subversive activities, and the dissemination of strategic narratives, especially in sometimes unsupervised social media environments ([Nissen 2015](#Nissen2015), p. 11).

To avoid the consequences of such antagonistic information activities and enhance the overall quality of social media discussions, media education should be promoted, which teaches people how to critically analyse today’s information-saturated online communications. Media education should cover all levels of education and address the following questions: how to decipher the meaning of the types of social media texts (e.g. memes) and understand why they are used in specific discussions; how to be source-critical in social media and how to detect the hidden intentions of those intermediating the texts; and how to recognise meaning creation aimed at gaining attention, misleading the audience and inciting conflict.

Academics in the social sciences and humanities play an important role in understanding the meaning creation under way in the digital public space. The Estonian National Defence Development Plan 2017–2026 stresses the importance of strategic communication as a developmental trend in national defence. Against this background, cooperation with academic institutions that deal with studying the dominant trends of meaning creation in social media should be encouraged. This is clearly a culture- and language-specific area of research, and thus, the research results from other countries cannot be uncritically applied to Estonia. Therefore, the academic research focused on the Estonian digital public space needs thoughtful coordination that facilitates cooperation between the research institutes and voluntary organisations (e.g. Propastop) focused on studying information attacks and media manipulation.

Training programmes to help raise the work quality of communication group moderators on social media platforms can also help to promote open digital communication. A positive initiative would also be the (national) recognition of the work of moderators, and awarding quality labels to well-moderated and dialogue-friendly social media communication spaces. This would require the development and dissemination of good practices for public social media debates. Having environments that have been recognised would encourage professionals, practitioners and active citizens to speak out on issues of social importance in social media. This would, in turn, promote open and reasoned public communication.

### References {-.subreferences #references-41}

<p id="Cohen1989">Cohen, J. 1989. Deliberation and Democratic Legitimacy. – Hamlin, A., Petit, P. (eds.). The Good Polity: Normative Analysis of the State. New York: Blackwell.</p>

<p id="Habermas1998">Habermas, J. 1998. Inclusion of the Other: Studies in Political Theory. Cambridge: Polity.</p>

<p id="Howard2011">Howard, R. G. 2011. Digital Jesus: The Making of a New Christian Fundamentalist Community on the Internet. New York: New York University Press.</p>

<p id="Jantunen2018">Jantunen, S. 2018. Infosõda. Tallinn: Kultuurileht.</p>

<p id="Kaldur2017">Kaldur, K., Vetik, R., Kirss, L., Seppel, K., Kallas, K., Masso, M., Anniste, K. 2017. Eesti ühiskonna integratsiooni monitooring. Meediakasutus ja infoväli. Tallinn: Kultuuriministeerium.</p>

<p id="Kasekamp2018">Kasekamp, A., Madisson, M.-L., Wierenga, L. J. 2018. Discursive opportunities for the Estonian populist radical right in a digital society. – Problems of Post-Communism, 66 (1), 47–58.</p>

<p id="2Madisson2016">Madisson, M.-L. 2016. The Semiotic Construction of Identities in Hypermedia Environments: The Analysis of Online Communication of the Estonian Extreme Right. Tartu: University of Tartu Press.</p>

<p id="Madisson-Ventsel2016">Madisson, M.-L., Ventsel, A. 2016. Autocommunicative meaning-making in online-communication of Estonian extreme right. – Sign Systems Studies, 44 (3), 326−354.</p>

<p id="Newman2017">Newman, N., Fletcher, R., Kalogeropoulos, A., Levy, D. A. L., Nielsen, R. K. 2017. Reuters Institute Digital News Report 2017. Reuters Institute for the Study of Journalism.</p>

<p id="Nissen2015">Nissen, T. E. 2015. Sotsiaalmeedia kasutamine relvasüsteemina. Tänapäeva konfliktide omadused. Tallinn: Tallinna Raamatutrükikoda.</p>

<p id="Opermann2018">Opermann, S. 2018. Youth news media use in Estonia. – Andersson, Y., Dalquist, U., Ohlsson, J. (eds.). Youth and News in a Digital Media Environment. Nordic-Baltic Perspectives. Göteborg: Nordicom, University of Gothenburg, 91–104.</p>

<p id="Orgse2018">Orgse, S. 2018. Facebooki arutelude modereerimine „Virginia Woolf sind ei karda!“ grupi näitel. BA thesis. University of Tartu.</p>

<p id="2Papacharissi2016">Papacharissi, Z. 2016. Affective publics and structures of storytelling: sentiment, events and mediality. – Information, Communication & Society, 19 (3), 307–324.</p>

<p id="Siibak2018">Siibak, A., Masso, A. 2018. ‘People who defend their homeland’: motivations for joining and being active in an anti-immigration group on Facebook. – Proceedings of the 9th International Conference on Social Media and Society (SMSociety). Copenhagen: SMSociety.</p>

<p id="2Tiidenberg2017">Tiidenberg, K. 2017. Ihu ja hingega internetis. Tallinn: Tallinna Ülikooli Kirjastus.</p>

<p id="Vihalemm2017">Vihalemm, P., Kõuts-Klemm, R. 2017. Meediakasutuse muutumine: internetiajastu saabumine. – Vihalemm, P., Lauristin, M., Kalmus, V., Vihalemm, T., Keller, M. (eds.). Eesti ühiskond kiirenevas ajas: Eesti elaviku muutumine 2002–2014 uuringu „Mina. Maailm. Meedia“ tulemuste põhjal. Tartu: Tartu Ülikooli Kirjastus, 251–278.</p>
