# Public urban space {.chapter2 .chapter2_section}
 <script>
  window.location = "sissejuhatus-2.html";
  </script>
## Introduction {-.chapter_section .chapter2_section .intro_section}
<h1>Avalik linnaruum</h1>
```{block, type='authors'}
<div class="author-links">**[Epp Lankots](#epp-lankots)**</div>
<div><a class="print-btn" href="print/EIA-2019-2.0.pdf"><i class="fa fa-file" aria-hidden="true"></i>Trükiversioon</a></div>
```

### Põhisõnumid {-.chapter2_section}

```{block, type='points'}
* In Estonia, the creation of public space has been unsystematic and fragmented between spatial plans with different focal points.

The creation of public space involves more than just the planning process. A narrow view that does not take into account the spatial impact of the development of transport, the education network and tourism among other areas does not help to achieve a better living environment. Creating an accessible, safe, seamlessly functioning and pleasant public space requires the public sector to combine the perspectives of different sectors and to manage the process.

* Material cultural heritage is a resource for improving the quality of public space and the living environment.

Taking into consideration the wider spatial impact of individual decisions when planning services in the counties will at once solve a number of important problems for the state. The exploitation and maintenance of cultural heritage will help to densify the centres of shrinking settlements and make small towns more attractive.

* Instead of relying on co-creation, the planning of public space in Estonian towns and cities has tended to focus more on procedure, being merely formally inclusive rather than informed by diverse knowledge and data.

The involvement of local communities and other stakeholders does not automatically guarantee high-quality public space, just like the collection of detailed data alone does not guarantee a democratic decision. It is important to strike a balance between the users of a space and the knowledge of experts. What is more, both experts and knowledge can be divided into different camps.
```

### Points of departure {-.chapter2_section}

In the history of European civilisation, the links between democracy and physical space have manifested themselves primarily through public space, which has not only provided a forum for public discussion but also marked the economic, political and cultural centre of an urbanising society. Today, the meaning of public space has expanded even further. Rather than a clearly defined section of urban space (a square or market place), public space is widely understood as space that is accessible to everyone and allows strangers to meet face to face ([Parkinson 2012](#Parkinson2012)). This shift in meaning results from the increased movement of people in the Industrial Age as work began to move further away from the home and contacts with other people and different kinds of people increased ([Sennet 1986](#Sennet1986)). Rapid technological development in the 20th century has significantly changed the spatial environment, how it is used and perceived, as well as the way it is studied. With the ‘spatial turn’ in the humanities and social sciences during the final decades of the 20th century, attention shifted to the relationship between space and society – how social relations are manifested in space and how space in turn shapes these relationships ([Lefebvre 1974](#Lefebvre1974); [Soja 1989](#Soja1989)). Public space as a political arena is one of the key interdisciplinary concepts describing this turn.

```{block, type='blockquote-left'}
Rapid technological development in the 20th century has significantly changed the spatial environment, how it is used and perceived, as well as the way it is studied.
```

As urbanisation accelerates, public space is under increasing pressure everywhere in the world, and the occupation of new areas for large-scale residential development has led to a loss of diversity in the urban space. There are no recognisable centres in the peri-urban residential areas and their role has been taken over by massive shopping centres on the outskirts of the city. The reduction of public space leads to a homogenised spatial environment, receding local identity and the loss of the attractiveness and competitiveness of regions. The UN sustainable development goals also specify public space and its accessibility as a global challenge to ensure quality of life in an urbanising world.

This chapter focuses on the quality of physical public space in Estonian urban environments, or densely populated areas, and on the specific conditions that have shaped these since the restoration of Estonia’s independence. Throughout the chapter, the creation of public space is treated as a set of spatial decisions of wider public interest, showing how public space engages everyone – including those who do not go to city squares. Related to public space in this sense is the concept of the spatial design (ruumiloome), introduced in Estonia in recent years, which broadens the understanding of spatial planning and architecture to include experts in various fields. Spatial plans and construction documents, on this view, are only some of the methods of spatial design and cannot be used to account for all changes occurring in space, including public space. Good public space is thus characterised by knowledge-based co-creation that cuts across the boundaries of different forms of ownership and considers different experiences of the use of space.

```{block, type='blockquote-right'}
The reduction of public space leads to a homogenised spatial environment, receding local identity and the loss of the attractiveness and competitiveness of regions.
```
To helps us understand the processes affecting Estonian public space, we need to be aware of the impact of our recent past. The post-war modernisation of Estonia was carried out under Soviet rule, during which Estonia developed into a largely urbanised society. Urban planning aimed at the mass-construction of new housing and the trend towards eliminating the urban-rural divide have significantly influenced the spatial structure of present-day Estonian settlements. Spatial changes on such a large scale – the construction of residential centres around agricultural holdings in rural areas, redeveloped city centres and new residential districts in the cities – were only possible in the context of the total state ownership of land. The individual or community had no say in issues relating to the living environment (e.g. choice of residence or discussion of regional development). Public space in the sense of both the common space between houses and public squares was an ideologically charged topic in Soviet urban planning, but smaller units of space (e.g. residential buildings or apartments) can also be considered part of the public sphere at the time due to state ownership or variations of it (e.g. cooperative ownership). This extended public sphere, peculiar to the Soviet system, was replaced by an at times extreme individualism in the 1990s ([Taul 2013](#Taul2013)). The tension between the private and public still largely influences spatial planning and the status of public space in Estonia. The manifestations and traces of this tense relationship are discernible at different levels in Estonian cities and towns. For example, after the privatisation of apartments, the appearance of Soviet-era apartment blocks has changed, with windows replaced and balconies converted in different ways for each apartment, which also affects the experience of the public space, and private cars now occupying the common space between the houses. On a larger scale, this is reflected, for example, in pragmatic planning that accommodates the wishes of private developers along the seafront in central Tallinn, with the resulting buildings in the port area forming long barriers that are otherwise more typical on the edges of the city.

```{block, type='blockquote-left'}
Spatial design – the formation and implementation of decisions that influence the development of space.
```
However, in the last decade, the creation of public space has made progress in Estonia. The inclusion of stakeholders in spatial planning is emphasised in the Planning Act, and the public sector as a whole has started to take its role as the commissioning party for public space more seriously. The architectural quality of public-sector buildings is improving, and architectural competitions have become the norm – juries for architectural awards (e.g. the annual awards of the Cultural Endowment of Estonia) composed of spatial design professionals are more often recognising public buildings and projects contributing to society more broadly. The ‘percentage law’ of 2011, which requires the use of 1% of the construction budget for public buildings to be spent on art, has enriched public space despite some legal problems, showing how public space can also promote the creation of culture in a narrower sense.

```{block, type='blockquote-right'}
The inclusion of stakeholders in spatial planning is emphasised in the Planning Act, and the public sector as a whole has started to take its role as the commissioning party for public space more seriously.
```
Against this background, however, it is important to emphasise that creating public space is not sustainable if it is reduced to government contracting – be it under the ‘percentage act’ or the town squares project as part of the Estonia 100 anniversary programme. Public space can only function to promote democracy if it is constantly possible to question and redefine it ([Levine 2010](#Levine2010)). This includes being open to experimentation, criticism from outside the institutions, and spontaneous citizen-initiated action that upsets the stability of the status quo to a certain extent. Non-institutional art, pop-up spaces and artworks, and the spontaneous use of space are some of the options for encouraging the creation of public space. Art in public space is also a means of drawing attention to public space as such, and thinking about the nature of the public sphere and how it is changing. The very essence of public space is debate, which arises from the interplay of different – also opposing – views, and through continually posing new questions that institutional and often decorative art or spatial design cannot evoke. Paradoxically, public space benefits if the tension between public contracting (for the creation of privately or publicly owned space) and informal practices remains.

### Articles in this chapter {-.chapter2_section}

All four articles in this chapter concede that the role of public space has not been sufficiently recognised in Estonian spatial planning, either through the treatment of the existing built heritage or the creation of new built environments. Nevertheless, recent years have seen a growing awareness of the public space among the population and a consensus among spatial professionals that such awareness is necessary. The articles highlight three major issues related to the creation of the physical public space.

The first important issue is the need to see the whole spectrum of public space. Toomas Paaver and Elo Kiivet explain in their article that good public space does not consist of only individual well-designed elements of the urban space, such as town squares; instead, it is the uninterrupted, seamless operation and the human scale that ensure the quality of public space. This includes offering a variety of modes of mobility and a safe and comfortable streetscape rich in experiences and open to spontaneous interventions, as well as perceived connections with surrounding buildings and non-public spaces. Paaver and Kiivet show how the narrowly focused sectoral documents and norms produced at the various levels of government and by different ministries represent conflicting values, thus creating divisions rather than coherence in the public space.

In the second article of the chapter, Triin Talk and Siim Raie similarly emphasise that if the full spectrum of costs and impacts were considered in public sector governance and investments in state-owned property, the state would be better placed to deal with the decaying and disused built heritage, which we are responsible for preserving for future generations. Investing in cultural heritage would be financially beneficial for society in the long run and would also be in keeping with globally recognised principles of sustainable development. Talk and Raie argue that the state’s property policy should include cultural heritage management as an objective. It is clear from Talk and Raie’s article, as well as the article by Paaver and Kiivet, that the quality of public space is a matter of national interest at a strategic level and fostering it requires it to be more clearly recognised as a task of the public sector.

```{block, type='blockquote-right'}
The quality of public space is a matter of national interest at a strategic level and fostering it requires it to be more clearly recognised as a task of the public sector.
```
The need for an integrated treatment of public space is related to another major theme: how could spatial design be used to help resolve major societal problems? The examples discussed in this chapter involve boosting regional development in shrinking cities, in particular by preserving the living environment on multiple levels and creating social cohesion through the co-creation of space. The article by Talk and Raie addresses the need to densify shrinking small towns through the use of heritage and the existing environment. The authors explain how, in addition to the campaign for building new town squares in historic centres, the local governments could further improve the quality of life by bringing more life to the town centres around these squares.

At the level of values, the co-creation of public space helps to reduce divisions in society and to connect different social groups. The article by Keiti Kljavin, Johanna Pirrus, Kaija-Luisa Kurik and Ingmar Pastak recognises that Estonia’s social development has reached a point where people are increasingly willing to have a say in the issues that shape their living environment. Paaver and Kiivet also point out that, since the public sector has often left the management of public space to the private owner and not committed to it, the whole issue has so far been largely the domain of civic activism. Neighbourhood associations and other associations of space users as well as several major publicity campaigns (e.g. the Reidi tee case in Tallinn) show how the public sector fails to value co-creation as a meaningful and constructive method, and public engagement in the planning process is often limited to the mere dissemination of information. Kljavin and others admit that co-creative planning of public space is unlikely, at least as long as Estonian planning practices at the local and national level continue to treat spatial activists as opponents. The authors also show how spatial activism and advocating for public space has boosted the development of Estonian civil society more broadly. In order for activism to have this kind of impact and for democratic society to continue to develop, spatial activists need the opportunity to constantly invent new forms of public participation and intervention. This means that having a seat at the discussion table should not require setting up a legal entity. At the same time, the authors acknowledge that the ability of activists to influence the creation of a cohesive public space is limited if the public sector does not agree on the general and long-term aims for the development of the public space in Estonia.

Public participation is related to the third important topic of the chapter – the quality of the debate informing spatial decisions. Renee Puusepp and Raul Kalvo write that one of the key principles of a planning process that considers different interests and takes into account a broad spectrum of experiences is the systematic collection, analysis and cross-use of spatial data. Spatial plans should be prepared through informed discussion where different solutions could be considered on the basis of visualised spatial data rather than relying on arbitrary, intuitive arguments as they have been to date. The parties would be able to rationally argue and make clearer and more comprehensible decisions with data-backed knowledge. Puusepp and Kalvo admit that, while we are close to the European average in terms of the collection of spatial data, the data collected does not influence the spatial design processes and decisions in Estonia or no clear connections are drawn between the data and spatial solutions. The authors believe that the public availability of up-to-date and accurate spatial data helps to improve the quality and overall efficiency of governance and decision-making processes.

Improving the collection and use of data will not, however, replace other forms of public participation. According to Kljavin et al., the quality of the debate and decisions on space depends on the balance of user experience and expert knowledge. This means that decision-making cannot be based solely on the preferences of stakeholders; instead, public participation involves the careful, balanced consideration of both expert knowledge and user experience.

### Estonia in the international context {-.chapter2_section}

It is problematic to assess the quality, or accessibility, of public space based on quantitative indicators, but one way of measuring it is to monitor the means of transport used by residents for their daily movements. It is widely acknowledged that settlements with a public space that is safe and pleasant to stay and move around in are pedestrian and bicycle friendly. In this field, Tallinn and Harjumaa county, which have the highest population density, as well as the rest of Estonia, are noticeably lagging behind the European average. According to the [2014](#Eurobarometer2014) Eurobarometer survey, 14% of the people in Finland, 23% in Denmark and 35% in the Netherlands, or 8% in Europe on average, used a bicycle to move around on a typical day. In Estonia, the figure was 5%, which is a few percentage points behind both Lithuania and Latvia. Estonia shows a clear trend towards motorisation: in 2018, 54.5% of the workforce used a privately owned or company car to go to work, while only 2.7% took a bicycle ([Statistics Estonia database 2018](#Statistics2018)). At the same time, international documents and contemporary planning recommendations make no reference to improving public space through allowing more room for cars in our streets ([Gehl Architects 2011](#Gehl2011); [Pere n.d](#Pere); [United Nations 2017](#United2017)). On the contrary, more and more cities around the world are moving towards closing the city centre to cars or significantly restricting traffic. Both the above figures and the fact that the use of urban space is centred around passenger cars show a gap between current international trends and the accessibility of public space in present day Estonia.

RStill, in line with international frameworks as well as local sectoral recommendations, we do display a relatively good awareness of the importance of public space in shaping a high-quality living environment. Estonia has recognised the cultural value of the built environment through the Davos Declaration (<a href="http://www.arhliit.ee/uudised/ean-kiidab-heaks-davosi-deklaratsiooni/">2018</a>) joined the European Landscape Convention (<a href="https://www.envir.ee/et/euroopa-maastikukonventsioon/">2017</a>) and, by signing the Leipzig Charter on Sustainable European Cities (<a href="https://ec.europa.eu/regional_policy/archive/themes/urban/leipzig_charter.pdf">2007</a>) confirmed its readiness to focus on creating user-oriented and high-quality public space. The importance of public space in improving the quality of the living environment and the built environment was first mentioned in the Estonian architectural policy (<a href="https://www.kul.ee/sites/kulminn/files/content-editors/eesti_arhitektuuripoliitika.pdf">2002</a>); clearly a product of its time, the policy attaches value to the outcomes of the chaotic 1990s in construction, emphasising the need to preserve architecture and the built environment primarily as part of the wealth of our national heritage. <a href="https://www.riigikantselei.ee/sites/default/files/riigikantselei/strateegiaburoo/ruumiloome_lopparuanne_.pdf">The final report by an expert group on spatial design</a> operating under the Government Office between 2017 and 2018, on the other hand, shows a shift away from valuing architectural quality towards a broad-based co-creation of space over the past 15 years. The report stands out against the backdrop of international agreements with its broad perspective, treating spatial design as ‘the formulation and implementation of decisions that influence the development of space’ (p. 5). The main recommendations of the working group are as follows: improving the spatial competence of the public sector, pursuing quality design, preserving cultural heritage, and public sector responsibility for promoting the quality of public space and the built environment.

### How do we move forward?{-.chapter2_section}

To create good public space, it is important first to be aware of the fact that objectives can be set on very different scales – from easily realisable changes to goals attainable in the longer term. The expected impact of major changes can be assessed on a smaller scale – for example, by testing temporary solutions to limit car traffic or by boosting street life with seasonal events. Various stakeholders in Estonia already have experience and knowledge of planning large public-space projects and of related debates; these can be used to pilot new changes.

Today, most local governments struggle with finding someone to take on a leadership role, as the planning of public space tends to be driven by pragmatic considerations rather than coordinated progress towards an ideal ([Traks 2019](#Traks2019)). Another aspect to consider when planning public space is how to make it accessible to everyone – including the elderly, people with disabilities, children and individuals with a reduced ability to cope – by implementing the principles of inclusive and universal design ([Astangu Vocational Rehabilitation Centre 2012](#Astangu2012)).
The goal to improve the living environment declared in the <a href="https://www.rahandusministeerium.ee/et/ruumiline-planeerimine/uleriigiline-planeering">Estonia 2030+</a> national spatial plan requires that the more specific plans not only outline a network of services and centres but also elucidate the concept of the quality of space itself. To formulate this requirement and oversee the interaction between the different areas of spatial planning, it is necessary to enhance the spatial competence of local governments, especially in the new municipalities created during the 2017 administrative reform.

```{block, type='blockquote-right'}
Public space must be accessible to all, including the elderly, people with disabilities and children.
```

But how do we make the physical public space work for shrinking small towns, so that the living environment would also survive in remote areas away from the larger centres? Adapting to sustainable shrinkage and consciously adjusting spatial planning to this has been seen as a solution here. In other words, we should think about how to adapt the town to the needs of the population and revitalise the town centre rather than only seeking growth ([Tintera 2018](#Tintera2018)). In seeking integrated solutions that bring together different areas, the creation of public space plays a pivotal role and can also help preserve and restore historic buildings, local identities and natural values ([Ministry of Finance 2015](#Ministryoffinance2015)). Equally important is the conscious development of a culture of participation in small towns. This calls for a significant shift in how planning goals are set – meeting the needs of the locals and maintaining a continuous public debate should be seen as an integral part of creating good public space.

### References {-.subreferences}

<p id="Astangu2012">Astangu Vocational Rehabilitation Centre 2012. Kõiki kaasava elukeskkonna kavandamine ja loomine. https://www.tallinn.ee/upload/Koiki_kaasava_elukeskkonna_kavandamine___loomine.pdf.</p>
<p id="Statistics2018">Statistics Estonia database 2018. Hõivatud soo ja töölkäimise viisi järgi.</p>
<p id="Eurobarometer2014">Eurobarometer 2014. Special Eurobarometer 422a. Quality of Transport. European Commission: Directorate-General for Mobility and Transport.</p>
<p id="Gehl2011">Gehl Architects 2011. Public Spaces & Public Life Study: City of Adeleide 2011. Copenhagen: Gehl Architects ApS.</p>
<p id="Lefebvre1974">Lefebvre, H. 1974. Production de l'espace. Paris: Éditions Anthropos.</p>
<p id="Levine2010">Levine, C. 2010. The paradox of public art: democratic space, the avant-garde, and Richard Serra’s “Tilted arc”. – Orum, A. M., Neal, Z. P. (eds.). Common Ground? Readings and Reflections on Public Space. New York: Routledge, 164–172.</p>
<p id="Parkinson2012">Parkinson, J. 2012. Democracy and Public Space: The Physical Sites of Democratic Performance. Oxford: Oxford University Press.</p>
<p id="Pere">Pere, P.-P. (n.d.). Jalakäijate ja jalgratturite roll linna brändi ning kohaliku ärikeskkonna kujundamisel. Juhtumiuuringud Tallinna peatänava projektile. Future Place Leadership.</p>
<p id="Ministryoffinance2015">Ministry of Finance 2015 2015. Suunised kahanevate piirkondade säästlikuks ruumiliseks planeerimiseks.</p>
<p id="Sennet1986">Sennet, R. 1986. The Fall of The Public Man. London: Faber.</p>
<p id="Soja1989">Soja, E. W. 1989. Postmodern Geographies: The Reassertion of Space in Critical Social Theory. New York: Verso.</p>
<p id="Taul2013">Taul, G. 2013. Monumentaalmaal kui avalik ruum. http://gregortaul.ee/articlesinest/monumentaalmaal-kui-avalik-ruum.</p>
<p id="Tintera2018">Tintera, J. 2018. Kuidas kaitsta kahanevat linna? – Eesti Arhitektuuriajakiri MAJA, 92 (winter), 96–105.</p>
<p id="Traks2019">Traks, M. 2019. Indrek Peil: Lokaalne linlane. – Eesti Arhitektuuriajakiri MAJA, 95 (winter), 6–21.</p>
<p id="United2017">ÜRO – United Nations 2017. New Urban Agenda. United Nations Conference on Housing and Sustainable Urban Development (Habitat III).</p>
