## Avalik ruum kui elukeskkonda siduv võrgustik {#chapter21 .chapter_section .chapter2_section}

```{block, type='authors'}
**Toomas Paaver ja Elo Kiivet**
```

```{block, type='points'}
* Avaliku ruumi hoidmine ja arendamine on avaliku sektori ülesanne ning see nõuab loomingulist lähenemist, professionaalsust ja osapoolte koostööd.
```

Iga kord, kui oma kodu uksest või väravast välja astume, siseneme avalikku ruumi. See on ühisruum, mille kaudu liigume ka kõigi mitteavalike ruumide vahel. Avalik ruum ei ole üksnes liikumiseks. See on olemisruum, mille terviklikust toimimisest sõltub ühiskonna sidusus ja elukeskkonna kvaliteet. ÜRO linnade tulevikuga ja kestliku inimasustusega tegelev programm ([United Nations 2017](#United2017)) määratleb avaliku ruumina kohti, mis on ligipääsetavad ja nauditavad kõigile ilma kasumitaotluseta. See on igapäevane ruum, aga ka arutluste ja meeleavalduste toimumise koht. Hea avalik ruum aitab tugevdada kogukondi, ergutada kodanikuosalust, vähendada segregatsiooni ja kasvatada sallivust, seega väljendub avaliku ruumi kvaliteedis ühiskonna ja demokraatia tervis.

```{block, type='blockquote-left'}
Hea avalik ruum aitab tugevdada kogukondi, ergutada kodanikuosalust, vähendada segregatsiooni ja kasvatada sallivust.
```
Meie elukeskkonda mõjutavad protsessid ja otsused eri valdkondades (transport, keskkonnakaitse, ettevõtlus, haridus, kultuur jm) moodustavad omavahel arvukaid ruumilisi seoseid, mis mõjutavad avaliku ruumi toimimist. See tähendab, et avalik ruum on habras ja kergelt kahjustatav, kui seda arendada tervikut nägemata. Avalik ruum pole eraldiseisev maastikuline või tehniline element, vaid seostub ümbritsevate hoonete ja mitteavalike ruumidega, luues terviklikke kooslusi nii funktsionaalses kui ka esteetilises mõttes.
Artiklis vaatleme füüsilist avalikku ruumi eelkõige linnakeskkonnas, avaliku sektori vastutust selle kaitsmisel ning selle mõtestamist õigusruumis ja valitsemises. Sissejuhatavas osas selgitame, millest koosneb avalik ruum ja toome välja avaliku ruumi kvaliteedi alused. Küsime, kuidas on taasiseseisvunud Eesti õigusruumis avalikku ruumi mõistet sisustatud, ja kirjeldame, kuidas on avalikku ruumi teadvustanud avalik sektor. Lõpetuseks pakume välja põhimõtted, kuidas kaitsta ja parendada avalikku ruumi.


### Avalik ruum on võrgustik, mis seob inimeste elu-, töö- ja tegevuskohad {-.chapter2_section}

Käsitusel avalikust ruumist kui avalikust asjast on enam kui paari tuhande aastane  ajalugu. Juba Rooma eraõiguses eksisteeris omandistruktuuri kontekstis esemete liik res extra commercium, mis seisis väljaspool käivet ehk ei saanud olla eraomandi ja tehingute objektiks. Selle hulka kuulusid muu hulgas res communes omnium, mille loodus on määranud kõigile, näiteks õhk, meri ja voolav vesi, ning res publicae ehk asjad, mida võiks iseenesest omandada, kuid nad on üldise kasu huvides määratud kõigile kasutamiseks, näiteks jõe kaldad ja avalikud teed ([Ilus 2000](#Ilus2000)).

```{block, type='blockquote-right'}
Avalikul omandil põhineva avaliku ruumi esmane ja keskne funktsioon on läbi ajaloo olnud inimeste elu sidumine.
```
Avalikul omandil põhineva avaliku ruumi esmane ja keskne funktsioon on läbi ajaloo olnud inimeste elu sidumine.[b]
“Avalikul omandil (res publicae) põhineva avaliku ruumi esmane ja keskne funktsioon on läbi ajaloo olnud inimeste elu sidumine.” Tänapäeval tähendab see elukeskkonna kvaliteedi mõistes ennekõike seda, et iga inimene tunneks end ruumis meeldivalt, mugavalt ja ohutult sõltumata vanusest, sissetulekust ja sõiduvahendi olemasolust ning et seda võimaldav ruum algaks igast kodust. Kui märkida kaardile kõigi inimeste teekonnad ja tegevuskohad ühe päeva jooksul, siis meenutab saadud kujutis võrgustikku. See avaliku ruumi kujutis kattub linnades paljuski tänavavõrgustikuga, kuid on tegelikkuses tunduvalt nüansirikkam.

```{block, type='casebox'}
Avalik ruum on enamasti riigi või kohaliku omavalitsuse omandis, aga vahel ka eraomandis. Kõige paremini väljendub avaliku ruumi võrgustikulaadne olemus linnade krundiplaanidel omandistruktuuri kaudu. Avalik omand moodustab seotud süsteemi, kuid eraomand koosneb üksikutest eraldiseisvatest maatükkidest.

<p class="caption" id="figure211"><span class="figure-number">Joonis 2.1.1.</span> Keila linna omandistruktuuri kaart (üldplaneeringu lähtematerjal)</p>

```
```{block, type='imgsource'}
<span class="imgsource-source">Allikas:</span> Sfäär planeeringud, 2019.
```

Avalik ruum koosneb peale tänavavõrgustiku parkidest, veekogudest, väljakutest, ühiskondlike objektide maa-aladest. Lisaks sisaldab see arvukalt teisi võrgustikke, mis on vajalikud eraomandi toimimiseks ja mis pakuvad avalikke teenuseid. Näiteks avaliku maa all on trassid, mis tagavad elektri-, vee- ja soojusvarustuse kodudes ja ärides. Avaliku ruumi maapealses osas on võrgustikud eri liikumisviisidele ja sõidukitele, et tagada inimeste ja kaupade ligipääs eraomandile. Ühistranspordisüsteem on avaliku ruumi oluline osa.

Avalik ruum ei ole ühene ega selgepiiriline, sest võib hõlmata eraomandit ning selles võivad sisalduda ruumiosad, mis pole igal ajahetkel kättesaadavad, on tasulised või mõeldud kasutuseks kindla kogukonna liikmetele. Sellised poolavalikud ruumid on näiteks piirdetaraga spordiplatsid, kaubamaja sisetänavad, kortermajade hoovid ja välikohvikud. Avalik ruum on hajus, kuna ruumil on omadusi, mille mõjud ulatuvad vahetust füüsilisest ümbrusest kaugemale. Nii vaated ja keskkonnamõjud kui ka hooned ja nende fassaadid on osa avaliku ruumi ühishuvist, mõjutades seda nii visuaalselt kui ka seal toimuvate tegevuste kaudu.

### Avaliku ruumi kvaliteedi määrab eelkõige selle sidusus kõigile kasutajatele {-.chapter2_section}

Avaliku ruumi peamine tunnus on vaba ligipääs kõigile nii füüsilises, sotsiaalses kui ka rahalises mõttes. Vaba ligipääs on tagatud siis, kui ruumi kasutajal on võimalik oma igapäevaseid ning ühiskondlike tegevusi iseseisvalt teha järjepidevas ruumis, milles ei ole takistusi või katkestusi. Keskse tähendusega on jalgsi liikuva inimese võrgustik. Kuigi tänavaruumis sisalduv sõidutee on avaliku ruumi vajalik osa, võib sõidukite liigne kiirus ja liiklustihedus selle muuta nii ebaturvaliseks, et see langeb nii-öelda avaliku ruumi kaardilt välja. Sel juhul kujuneb iga ülekäigurada ja kõnnitee väga oluliseks võrgustiku elemendiks. Kui need osad on kitsad, omavahel sidumata, ohtlikud või ebameeldivad, siis võrgustik katkeb, sest tänavad ja ristmikud ei toimi enam kõigile ruumikasutajatele liikumis- ega olemisruumina.

```{block, type='casebox'}
Tartus 2016. aastal koos Eesti Rahva Muuseumi (ERM) rajamisega uuendatud Roosi tänav rõhutab nii läbivates ruumilistes ideedes kui ka täpsemates lahendustes kesklinna ja muuseumi sidumist jalgsi liikuvale inimesele. See on võimendanud ruumitunnetust, milles ERM ei ole eraldiseisev objekt, vaid seotud Tartu kesklinna avaliku ruumi kui võrgustikuga, andes lähtepunkti ka järgmistele sammudele piirkonna elukeskkonna parendamisel.

<p class="caption" id="figure212"><span class="figure-number">Joonis 2.1.2.</span> Roosi tänav Tartus</p>

```
```{block, type='imgsource'}
<span class="imgsource-source">Allikas:</span> Foto autor Triin Pitsi.
```

Autostumise tulemusel on avalikku ruumi sageli arendatud lihtsustatult, käsitledes seda pigem transporditaristuna ja juhindudes sõiduautost ja sõiduteede võrgustikust. Paljude riikide kogemus näitab, et see viib kergesti elukeskkonna halvenemiseni ja ligipääsetavuse vähenemiseni ([Gehl 2015](#Gehl2015)). Kui avalik ruum ei toimi inimsõbraliku võrgustikuna, siis kolivad autodesse ka need, kes muidu autot ei kasutaks, ja see toob linnades kaasa paratamatu ummistumise. Jalakäijale suunatud sidus avalik ruum tingib ka ühistranspordi aktiivse kasutamise. Kuigi ühe osa avaliku ruumi kvaliteedist moodustab võimalus liikuda sõiduautoga, on hea elukeskkonna eelduseks arusaam, et avalikus ruumis on inimene alati sõidukitest tähtsam.

```{block, type='blockquote-left'}
Autostumise tulemusel on avalikku ruumi sageli arendatud lihtsustatult, käsitledes seda pigem transporditaristuna ja juhindudes sõiduautost ja sõiduteede võrgustikust.
```

Sidus avalik ruum on üleilmselt oluline arengusuund elukeskkonna kvaliteedi parandamisel. ÜRO säästva arengu üks eesmärke on tagada aastaks 2030 universaalne juurdepääs kaasavale ja ligipääsetavale avalikule ruumile ning rohealadele, sest hästi kujundatud ja hooldatud sidus avalik ruum tagab madalamad kuritegevuse näitajad, võimestab sotsiaalselt tõrjutud ühiskonnarühmi ning on eeldus õnnelike ja tervete kodanike heaolule. Kvaliteetne avalik ruum on linnade majandusliku, keskkondliku ja ka kultuurilise konkurentsivõime alus ([United Nations 2017](#United2017)). Avalikku ruumi esikohale seadev kohaloome katusorganisatsioon mittetulundusühing Project for Public Spaces ([2007](#Project2007)) nimetab avaliku ruumi majandusliku kasuna näiteks kinnisvara väärtuse tõusu, suurenenud väikeäride tihedust ja kasvavat käivet. Hea avalik ruum vähendab õhu- ja mürareostust ning toetab liigirikkuse kasvu

```{block, type='blockquote-right'}
Kuigi ühe osa avaliku ruumi kvaliteedist moodustab võimalus liikuda sõiduautoga, on hea elukeskkonna eelduseks arusaam, et avalikus ruumis on inimene alati sõidukitest tähtsam.
```
Avaliku ruumi kui võrgustiku kvaliteedi esmane omadus on teekondade jätkuvus, mugavus ja ohutus nii lastele, eakatele kui ka erivajadustega inimestele, lähtudes igast kodust, töö- ja tegevuskohast; aga niisamuti ka terviklik ökosüsteem. Kvaliteetset avalikku ruumi iseloomustab ka selle üksikosade, iga tänava, platsi ja pargi esteetika, tajuelamused ja sümboolsed tähendused. Ruumikasutajate eri soovidele ja võimalustele vastab mitmekesine avalik ruum, mis võimaldab valikuvabadust ja iseorganiseerumist. Avaliku ruumi terviklikkuse ja kvaliteedi tagab kõikide nende aspektide kohaspetsiifline ning ruumiline läbimõeldus nii ruumi planeerimise, projekteerimise, ehitamise kui ka kasutamise järgus.

### Avalik ruumi mõiste on Eesti õigussüsteemis sisustamata {-.chapter2_section}

Nii nagu avalik õigus eraõiguse kõrval võimaldab eraõiguslikel isikutel end riigis kindlalt tunda ja ühiskonnal tervikuna areneda, vajab eraomandis ruum selle hüvede kasutamiseks enda kõrvale avalikku ruumi ([Paaver 2013](#Paaver2013)). Avalik ruum ei teeni ise kasumit, vaid on alus nii ettevõtlusele kui ka elukeskkonna arengule.

Eesti õigusruumis ei ole avaliku ruumi mõistet otsesõnu sisustatud. Meie õigusruumis leidub määratlus mõistele avalik koht (reklaamiseaduse § 2, korrakaitseseaduse § 54), mis on suunatud igapäevaelu korraldamisele, turvalisuse ja korrashoiu tagamisele, kuid mitte ruumi püsimisele, arendamisele või parendamisele.

```{block, type='casebox'}
Eesti avaliku sektori, sealhulgas riigiettevõtete vastuolulist käitumist avaliku ruumiga iseloomustab juhtum, mil 2018. aastal müüs riik Tallinna linna vastuseisust hoolimata avaliku Kompassi väljaku kinnisvarafirmale, kes seejärel taotles kinnistule kõrghoone rajamist, nähes alternatiivina üksnes suletud eraaeda. Pole seadusi, mis takistaks sellist müüki või avaliku ruumi, näiteks tänava või pargi võõrandamist eraomandisse või nõuaks küsimuse avalikku arutamist. Riik on omavalitsuse asetanud olukorda, mis raskendab omaniku tahte puudumise korral avaliku ruumi kvaliteetset arendamist või isegi hoidmist. Taoline olukord tekib siis, kui riik või omavalitus seisab pigem oma tulude eest, jättes avaliku ruumi tagaplaanile.

<p class="caption" id="figure213"><span class="figure-number">Joonis 2.1.3.</span> Kompassi väljak Tallinnas</p>

```
```{block, type='imgsource'}
<span class="imgsource-source">Allikas:</span> Maaamet.
```

Aastatel 1993–2002 kehtis asjaõigusseaduse § 9 lg 2, mis sisult kattus Rooma eraõiguse res publicae’ga ning mõjutas maaomandi struktuuri: „Avalik asi on asi, mis kuulub riigi- või munitsipaalomandisse ja on oma ühiskondliku olemuse tõttu kasutatav igaühe poolt nagu territoriaal- ja sisemeri, laevatatavad veekogud, avalikud tänavad, väljakud ja pargid“. “Nüüdseks tühistatud määratlus oli aluseks maareformile ning sedakaudu suurele osale senisest avaliku ruumi struktuurist, sest avalikke tänavaid või parke üldjuhul ei erastatud ega tagastatud. Siiski on nii maareformi kui ka hilisemate tehingute (nt munitsipaal- ja riigimaa müügilepingud) mõjul osa avalikust ruumist saanud eramaaks. Praeguses õigusruumis puudub avaliku asja sarnane üldmõiste, mille alusel saaks avaliku ruumi ulatuses piisavalt selgelt ja püsivalt kokku leppida.

Avalikku ruumi sidusust ja ligipääsetavust mõjutab seegi, kuidas on reguleeritud õigus liikuda eramaal. Aastatel 1993–2014 kehtinud asjaõigusseaduse § 142 keelas omaniku loata erakinnistul viibimise. Aastal 2014 viidi võõra maatüki kasutamist reguleerivad sätted keskkonnaseadustiku üldosa seadusesse, kuhu muu hulgas lisati § 33 lg 3: „Omanik ei või keelata eratee ega raja kasutamist jalgsi, jalgrattaga ega muul sellesarnasel viisil liikumiseks, kui kasutus põhineb väljakujunenud taval ega ole talle koormav“. See säte on veel vähe juurdunud, kuigi on abiks avaliku ruumi sidususe tõstmisele.


Avalik ruum saab toimida ka eramaadel, kuid sel juhul nõuab võrgustiku sidususe ja püsimise tagamine veelgi rohkem tööd avalikult sektorilt. Viimastel aastatel on avaliku ruumi mõiste jõudnud mõnesse planeeringusse ja juhendisse, näiteks 2018. aastal Rahandusministeeriumi koostatud juhend „Nõuandeid üldplaneeringu koostamiseks“ ütleb, et õigusruumis määratlemata mõistena „on mõistlik avaliku ruumi ja väärtuste teemad läbi arutada, neis kokku leppida ning sõnastada ja määrata üldplaneeringu koostamisel“. Niisamuti märgib ruumiloome ekspertrühma 2018. aasta lõpparuanne, et „kõigile kättesaadav kvaliteetne avalik ruum on arenenud demokraatliku riigi oluline tunnus“. See tähendab, et eri tasandi planeerimisvaldkonnad on teadvustamas avaliku ruumi mõistet, mis seni on jäänud juhuslikuks või sootuks tähelepanuta.

### Avalik sektor ei ole end üldjuhul teadvustanud avaliku ruumi esindaja ja tellijana  {-.chapter2_section}

Avalikku ruumi ei ole planeerimisseaduses nimetatud ega käsitletud ning see on viinud planeeringute fookuse kas kasutusotstarbe määratlemisele või konkreetsetele objektidele, hoonetele, taristule või sõiduteedele, mitte neid siduvale ühisruumile. Kui omavalitsus keskendub ainult üksikisikute huvide tasakaalustamisele seadusekohase menetluse kaudu ja kui puudub isik, kes avalikku ruumi telliks või esindaks, võib see jääda tagaplaanile ka planeerijate või arhitektide töös. Sellest on tulenenud ka osa kodanike õigustatud rahulolematus planeeringutega või nende alusel loodud ruumiga.

```{block, type='casebox'}
 Liiga kitsas kõnnitee Tallinnas Põhja puiesteel ei võimalda liikumist kas või lapsevankri- ga, seal ei mahu kõrvuti käima ega vastutulijast mööduma, mugavusest või ohutusest rääkimata. Avaliku ruumi võrgustik on katkestatud. Ruumi kõnnitee laiendamiseks on piisavalt isegi ilma sõiduradade arvu vähendamata, aga linnavalitsus ei ole seda teinud.

<p class="caption" id="figure214"><span class="figure-number">Joonis 2.1.4.</span> Tallinna Põhja puiestee</p>

```
```{block, type='imgsource'}
<span class="imgsource-source">Allikas:</span> Foto autor Reio Avaste.
```

Omavalitsused on mõnikord eelistanud ruumiotsustes erahuve ja kahjustanud sellega avalikku ruumi põhjendusel, et puudub piisavalt selge alus avaliku ruumi püsimist või selle kvaliteedi suurendamist eraomanikult nõuda. Mõni omavalitsus on siiski seda alust tugevdanud avalikku ruumi teadlikult väärtustava üldplaneeringuga, näiteks Tartu kesklinna üldplaneeringus on avalik ruum eraldi joonistel ja peatükina esile tõstetud. Siiski ei sobi aeglaselt muutuvate dokumentidena ja liiga jäigalt fikseerituna planeeringud ka avaliku ruumi paindlikuks sammsammuliseks parendamiseks. 

```{block, type='blockquote-right'}
Eri tasandi planeerimisvald- konnad on teadvustamas avaliku ruumi mõistet, mis seni on jäänud juhuslikuks või sootuks tähelepanuta.
```

Tänavad ja pargid on enamasti avalikus omandis, kuid see ei taga avaliku ruumi sidusust. Tänavate ehitamise alus ei ole üldjuhul detailplaneeringud, vaid tee-ehitusprojektid, mida lahendatakse üksnes insenertehniliselt ega avalikustata. Nii planeeringute kui ka teeprojektide aluseks on enamasti standard EVS 843 (Linnatänavad), mille sisu näeb tervikliku võrgustikuna sõiduteid, aga mitte avalikku ruumi. Normatiivide mehaanilise rakendamise tõttu kipuvad linnaruumis domineerima sõiduteed ja autokesksus. Lühiajalistes ruumiotsustes, näiteks talvises tänavahoolduses või ehitusaegses liikluskorralduses, võimenduvad sõiduautode ületähtsustamine ja jalakäija unustamine veelgi. Nii võib avalik sektor tekitada suuremaidki katkestusi avalikus ruumis kui eraomand.

Kohalikel omavalitsustel ei ole võimalik avalikku ruumi eirata, sest see on kõigis asulates olemas, pikema aja jooksul kujunenud ja enamjaolt aktiivses kasutuses. Omavalitsused üldjuhul haldavad peaaegu kogu avalikku ruumi ja püüavad seda võimete piires edasi arendada. See on sõltunud aga eelkõige konkreetse omavalitsuse ametnike mõtteviisist.

```{block, type='blockquote-left'}
Normatiivide mehaanilise rakendamise tõttu kipuvad linnaruumis domineerima sõiduteed ja autokesksus.
```

Nii riigi Maa-amet kui ka riigiettevõtted ja omavalitsused on eraomandisse võõrandanud maatükke, mida kasutatakse avaliku ruumina või mida oleks loomulik selleks kavandada (joonis 2.1.3). Sellise tehingu korral satuvad nii linnaelanike kui ka uue omaniku õigused praeguses õiguskorras ebaselgele pinnale, milles vaidluste tulemust ei saa ennustada.

Sellegipoolest leidub eraomanikke, kes on ise mõistnud avaliku ruumi vajalikkust ning on seda arendanud vahel tõhusamaltki kui kohalik omavalitsus. Tavaliselt toimub see juhul, kui ühe arendaja omandis on suurem ala. Avalik ruum väärtustab ja suurendab ala atraktiivsust nii kasutajate kui ka äride silmis. Ometi kipuvad sellised avalikud ruumid jääma laiema võrgustikuga sidumata, kui omavalitsus või omanik ei pööra tähelepanu avaliku ruumi püsimisele või sidumisele ümbrusega.

Kuna avaliku ruumiga ei ole avalikus sektoris piisavalt teadlikult tegeletud, on see jäänud paljuski kodanikuaktiivsuse töömaaks. Asumiseltsid ja huvigrupid on koostanud omal algatusel avaliku ruumi visioone, korraldanud aktsioone ja võtnud enda kanda nii koostööd kui ka vaidlusi nii eraomanike kui ka omavalitsustega. Esinduslikumate avalike ruumide loomise nimel on olulisi samme teinud Eesti Arhitektide Liit (nt EV100 arhitektuuriprogramm „Hea avalik ruum“ koostöös kohalike omavalitsustega). Vabakonna ja erialaorganisatsioonide hoogustunud tegevus näitab, et avaliku ruumi sidusus ja kvaliteet teevad ühiskonnale tõsist muret. Mõneti on aktiivsed kodanikud ja kolmanda sektori ühendused asunud ise avaliku ruumi esindajaks või tellijaks. Kõik sedasorti ühiskondlikud ettevõtmised suudavad pakkuda vaid üksikuid ja ajutisi lahendusi, mis ei asenda pidevat eksperditeadmistel põhinevat tööd avaliku ruumi kui terviku parandamiseks.

```{block, type='blockquote-right'}
On oluline, et riik ja riigiettevõtted ei kahjustaks suurarenduste tellijatena ise avalikku ruumi.
```
Riigi ja omavalitsuse ametkonnad, mille otsused loovad või muudavad avaliku ruumi, lähtuvad tihti kitsalt oma ametkonna fookusest. Puuduvad ametkondi siduvad üksused, kes avalikku ruumi tervikliku võrgustikuna esindaks ja kaitseks, selleks vajalikke lahendusi looks ning teeks avaliku ligipääsetavuse ja inimsõbraliku ruumi huvides sihipärast koostööd erasektoriga.

### Avalik sektor ei ole end üldjuhul teadvustanud avaliku ruumi esindaja ja tellijana  {-.chapter2_section}

Avalik ruum on keerukas võrgustik ja muutumises olev struktuur. Samamoodi nagu tehnilised võrgustikud (veevarustus, elektrisüsteem jm), vajab avalik ruum toimimiseks ja arenguks võrguvaldaja järjepidevat tööd. Avaliku ruumi võrguvaldaja on avalik sektor, kes saab kaitsta ja parendada avalikku ruumi.

```{block, type='casebox'}
Avaliku ruumi määratlemisel ja kvaliteedikriteeriumide kehtestamisel võib eeskuju võtta ÜRO koostatud juhendmaterjalist „Global Public Space Toolkit: From Global Principles to Local Policies and Practice“ (2015), kust leiab eriilmelisi praktilisi näiteid nii linna- kui ka riigivõimule ruumi ja poliitika loomiseks ning kodanikuühiskonna väärtustamiseks. NACTO ja Global Designing Cities Initiative’i koostatud tänavate kujundamise juhendid „Global Street Design Guide“ keskenduvad avalikule ruumile ja linnatänavate ümbermõ- testamisele. Samuti on võimalus pöörduda kohaloome põhiorganisatsiooni ehk Project for Public Spaces lihtsate kontrollküsimuste ja juhendite poole.
```

Avaliku ruumi võrgustiku valdajana on omavalitsusel õigus ja kohustus seista avaliku ruumi eest kõigis oma otsustes. Riigi ülesanne on olla linnade ja valdade partner, kuid ka õigusruumi looja ning erandjuhul ja vajaduse korral kodanike kaitsja, kui omavalitsus mingil põhjusel avaliku ruumi eest piisavalt ei seisa. Samuti on oluline, et riik ja riigiettevõtted ei kahjustaks suurarenduste tellijatena ise avalikku ruumi.

Nii linnade, valdade kui ka riigi tasandil on mõistlik kaaluda pädevate meeskondade moodustamist, kes suudavad kaitsta eri valdkondade koostöös avalikku ruumi kui sidusat võrgustikku. See ei nõua halduskoormuse kasvu, vaid pigem formaalsete menetluste asendamist pideva sisulise tööga.

Kuna avalik ruum moodustab olulise osa igapäevasest eluruumist,  on mõistlik kaasata avalikkus otsustesse, mis jäävad vormiliselt küll planeerimisregulatsioonist välja, kuid millel on tuntav mõju avalikule ruumile, sest paljusid ruumiotsuseid (nt kas mingi koht jääb avalikuks pargiks, tänavaks, mänguväljakuks, metsaks või mingi läbipääs avatuks) ei langetata planeeringutega, vaid tihti enne või pärast planeerimist, näiteks müügitehingute või liikluskorraldusega. Ideaaljuhul on avalik ruum püsivalt avalikus omandis, kuid tulenevalt Eesti senistest julgetest erastamisotsustest peab arvestama, et riik on juba teinud valiku, et avaliku ruumi sidusus ja kvaliteet tuleb tagada ka paljudel eramaadel. Samuti on oluline, et avalik sektor avalikule ruumile vajalikke maid mõtlematult ei võõrandaks, vaid seaks tehingutes avaliku ruumi tagamiseks tingimused ning oskaks vajalikke maid ka targasti omandada.

Igal omavalitsusel pole mõistlik oma määrustes või planeeringutes avaliku ruumi olemusele sisu otsida. Üldpõhimõtted saaksid selgelt ja ühesuguselt kehtida kogu riigis. Õigusruumi selguse vajadusele rõhub ka ruumiloome ekspertrühma lõpparuanne:

**„[d]Õigusaktides tuleb luua senisest selgemad alused ruumiloomele tervikuna, haarates seostatuna kõiki ruumiotsuseid. Seaduses tuleb seostatult käsitleda ruumiloome põhimõtteid ja mõisteid. Avaliku ruumi olulisuse rõhutamine ruumiloomes ja kvaliteedinõude sõnastamine annavad parema aluse kvaliteetse avaliku ruumi ja ehitatud keskkonna rajamiseks ning eelnõude ruumimõju hindamiseks“[e]**

Nii riik kui ka omavalitsused peavad teadvustama oma rolli avaliku ruumi võrguvaldajana või tellijana, pidades sealjuures lugu igast ruumikasutajast. 

```{block, type='casebox'}
Linna ruumilise kvaliteedi tõstmisel on keskne tähtsus avaliku ruumi kui tervikliku võrgusti- ku sidususel, tihedusel ja mitmekesisusel. Näiteks Tallinna vanalinna ümbritsevat pargivööd saab arendada avaliku ruumi osana, võimaldades mugavat ülepääsemist sõiduteedest, laiendades jalakäiguruumi ja avades uusi kvartalisiseseid läbipääse. Nii saab ühendada inimesele mugavalt hulga ülelinnalise tähtsusega ühiskondlikke hooneid, väljakuid, tä- navaid ja parke, mille kaudu saab Tallinn kujuneda tunduvalt inimsõbralikumaks linnaks.

<p class="caption" id="figure215"><span class="figure-number">Joonis 2.1.5.</span> Väljavõte EKA Lõpetamata Linna projektist</p>

```
```{block, type='imgsource'}
<span class="imgsource-source">Allikas:</span> Kavakava arhitektid.
```

### Kokkuvõte  {-.chapter2_section}

Hästi toimiva ühiskonna ülesanne on hoolitseda, et inimene tunneks end ruumis hästi mitte ainult kodus, tööl ja autos, vaid ka avalikus ruumis. Avalikku ruumi mõjutab peaaegu iga ruumiotsus. Avaliku sektori tuumülesanne on ruumi mõjutavate otsuste ja lahenduste positiivseid mõjusid kaitsta ja võimendada ning negatiivseid mõjusid ennetada või takistada. Avaliku ruumi terviklikkus on üldkehtiv avalik huvi ja seal ei saa juhinduda ühe teema või ruumikasutaja eelistamisest, näiteks sõiduteede või omaniku vabaduste ülimuslikkusest. Avalik ruum vajab kaitsmise kõrval ka visioonidel põhinevat strateegilist arendamist, sealhulgas pidevat ruumilist seostamist iga rajatava hoone, sõidutee ja era-arendusega. Muu hulgas annab avalik ruum võrgustikulise ruumiobjekti tähenduses selgema aluse linnaarhitektide tööle ja tasakaalus planeeringulahendustele.

```{block, type='blockquote-left'}
Avalik ruum vajab visioonidel põhinevat strateegilist arendamist, seal hulgas seostamist iga rajatava hoone, sõidutee ja eraarendusega.
```

Kuigi Eesti lähiajaloo õigusruumis ja valitsemistavades on avalik sektor keskendunud ruumi parendamise asemel pigem seda suunavate dokumentide menetlemisele, on nüüdseks hakatud sisulises mõttes teadvustama ruumi ja elukeskkonna tulevikku. 2015. aastal lisati planeerimisseadusesse (§ 8) elukeskkonna parendamise põhimõte ning ehitusseadustikku (§ 1) eesmärk tagada ehitatud keskkonna eesmärgipärane toimivus ja kasutatavus. Need üldised sätted jäävad deklaratiivseks, kui riigis ja omavalitsustes ei käivitu teadlik töö avaliku ruumi järjekindlaks parendamiseks, milleta on võimatu elukeskkonda tervikuna edendada.

Erinevalt vaba ettevõtluse arendustest saab avalik sektor avaliku ruumi arendamist ise teadlikult ja strateegiliselt suunata. Avalikust ruumist ja selle arendamisest sõltuvad erainvesteeringud, arendajate valikud, inimeste elu- ja töökohavalikud, mida planeeringutega jäigalt reguleerida ei saa. Mõistlik on avaliku ruumi või ühisruumi mõiste kasutusele võtta mitte üksnes seadusraamistikus, vaid ühe alusena killunenud valdkondlike ruumiotsuste kokkutoomisel.

Avalik ruum kui elukvaliteeti oluliselt mõjutav võrgustik vajab pidevat tähelepanu ja tahet seda paremaks arendada. See nõuab peale tehniliste teadmiste ja oskuste loovust, head ruumitunnetust ja valdkondadevahelist sünergiat. Elukeskkonna parendamist sooviv avalik sektor mõtleb ja tegutseb kodanike ühishuvides.

Aastal 2018 valminud ruumiloome ekspertrühma lõpparuande üks ettepanekuid on laiendada elukeskkonna parendamise põhimõtet selgemalt kogu ruumiloomele. Et see toimiks, peavad avalikku ruumi igas oma otsuses väärtustama nii ettevõtjad kui ka kodanikud, nii omavalitsused kui ka riik.

Turvalisust ja heaolu kasvatab eelkõige aktiivne ruumi kasutus ([Worpole ja Knox 2007](#Worpole2007)), seega on tähtis ka ruumi iseorganiseerumine ja vabakasutus. Ise- ja koosloomine suurendab ühtlasi elanike kogukonna- ja omanikutunnet. Ruumiloome formalismist vabanemise eelduseks on mõtteviisi muutus, aga ka õigusruumi toetus. Avalik ruum paraneb, kui võrgustiku terviklikkust ja mitmekesisust tähtsustatakse järjepidevalt nii suurtes otsustes kui ka pisiasjades. Sellega koos püsib ja paraneb kogu ühiskonna ja demokraatia tervis.

### Viidatud allikad {-.subreferences}

<p id="Gehl2015">Gehl, J. 2015. Linnad inimestele. Tallinn: Eesti Kunstiakadeemia, Yoko Oma.</p>
<p id="Ilus2000">Ilus, E. 2000. Rooma eraõiguse alused. Tallinn: Ilo Print.</p>
<p id="Paaver2013">Paaver, T. 2013. Mis on avalik ruum – avaliku ruumi käsitlustest ruumilises planeerimises. –Roose, A. (toim.). Peatükke planeerimisest. Protsesse, meetodeid ja näiteid. Tartu: Tartu Ülikool, 51–62.</p>
<p id="Project2007">Project for Public Spaces 2007. What is placemaking? https://www.pps.org/article/what-is-placemaking.</p>
<p id="United2017">United Nations 2017. New Urban Agenda. United Nations Conference on Housing and Sustainable Urban Development (Habitat III).</p>
<p id="Worpole2007">Worpole, K., Knox, K. 2007. The social value of public spaces. Joseph Rowntree Foundation.</p>