# Aruteluruum {.chapter4 .chapter4_section}

## Sissejuhatus {-.chapter_section .chapter4_section .intro_section}
<h1>Aruteluruum</h1>

```{block, type='authors'}
**[Indrek Ibrus](#indrek-ibrus)**
```

### Põhisõnumid {- .chapter4_section}

```{block, type='points'}
* Eesti toimetusliku kontrollita aruteluruum on afektiivne

Avalikes aruteludes on hakanud tooni andma sotsiaalmeediaplatvormidel või mujal veebis loodud keskkondades harrastatav afektiivne ehk üliemotsionaalne kõnepruuk – uudislike olukordade kiire sildistamine, mure või ärrituse väljendamine, eelarvamustest lähtuvad halvustavad hoiakud, pahatihti vihakõne. Et afektiivne suhtlus ei võimalda mõistmisele suunatud ühiskondlikku dialoogi ning toetab väärinfo levikut, tuleb sellele vastu seismiseks pakkuda meediaharidust laiemale elanikkonnale.

* Tõenduspõhist ekspertsust nõudvad arutelud võivad teadlastele olla frustreerivad

Eesti ajakirjandusväljaanded on „teaduse usku“, andes sageli sõna nii teadlastele kui ka teistele ekspertidele. Suurema ühiskondliku tähelepanu alla tõusvad keerukad ja tõendust vajavad arutelud toovad aga sageli kaasa ideoloogilisi rünnakuid teadlaste vastu, nende asjatundlikkuse tühistamist. Ajakirjanduses leidub puhuti ka karikatuurseid käsitlusi teaduslikest aruteludest. Ajakirjandusväljaanded peaksid seetõttu otsima uusi viise tõenduspõhiseid arutelusid tasakaalukamalt vahendada.

* Eesti noored hoiavad avalikest aruteludest eemale

Eesti noored internetikasutajad tarbivad küll sotsiaalmeediat uudisteni jõudmiseks enam kui ajakirjandusväljaandeid, kuid peavad viimaseid tõeste uudiste allikana usaldusväärsemaks. Noored ei löö veebipõhistes aruteluruumides kuigivõrd kaasa, kuna pelgavad sealseid hierarhiaid ja afektiivset kõnepruuki. Vahendatud aruteluruumide asemel eelistatakse näost näkku kõnelusi ning ühiskonda panustatakse pigem konkreetsete päriseluliste ettevõtmiste kaudu. Meediajuhid hindavad kõrgelt noorte meediakirjaoskust.
```

### Lähtekohad {- .chapter4_section}

„Ruumiga“ on üldiselt häda. „Ruum“ on käepärane kujund, kui soovitakse kõnelda keerulistes seostes tegutsejatest ja nende omavahel seotud tegevustest. „Kultuuriruum“, „küberruum“, „keeleruum“, „majandusruum“, „õigusruum“ jne – neid mõisteid iseloomustab korraga nii teatud sisemise ühtsuse kui ka mitmekesisuse eeldus. Need ruumid on ka üldjuhul piiritletud, oluline on eristatus välisest, teistsugusest ruumist. Sageli jääb lahtiseks küsimus, kuidas need kujundlikud ruumid seonduvad päris ruumiga – sellega, kus inimesed füüsiliste objektina suurema osa oma ajast veedavad. See küsimus on aktuaalne ka siinses aruandes. Kui ülejäänud inimarengu aruande peatükid pakuvad eri vaatenurki sellele, kuidas ruumisuhted ja -korraldus mõjutavad ühiskonna ja demokraatia käekäiku, siis siin arutame, kuidas kujuteldavas – Eesti elanike aruteludest tekkivas ruumis arenevad suhted mõjutavad omakorda nii Eesti inimarengut, demokraatiat kui ka n-ö pärisruumis toimuvat.

Niisiis, kus on Eesti aruteluruum ja millest see koosneb, kes seda loovad? Eesti aruteluruumi loovad kõik Eesti elanikud, Eestist mõtlejad ja kõnelejad igal pool üle ilma. Digiajastu eripära on, et see aruteluruum saab tõesti ühes rütmis ja suhteliselt vahetult üleilmselt toimida. Samal ajal on aga arenenud selle sisemine temaatiline ja ideoloogiline killustatus – Eestist räägitakse üha enam eraldatult, erinevates poolsuletud aruteluruumides ja erinevalt. Selles vastuolus väljendub ka nüüdisaja aruteluruumide peamine pinge – ühelt poolt eeldab demokraatia toimimine ühiskonna laialdast osalemist diskussioonides ning nende pinnalt kujunevaid ühiskondlikke kokkuleppeid ja konsensust, teiselt poolt on vajalik ka erinevate vaadete ja unikaalsete ideede rikkus, et ühiskonnal oleks edasiminekuks valida lai valik alternatiivseid ideid ja teadmust. Alternatiivsed ideed vajavad aga arenguks ja küpsemiseks mõnevõrra eristatud ja iseseisvaid suhtlusruume.

```{block, type='blockquote-left'}
Avaliku aruteluruumi ülesanne demokraatlikus ühiskonnas on toota korraga nii ideederikkust kui ka sellest rikkusest parimate arengusuundade väljasõelumist.
```

Avaliku aruteluruumi ülesanne demokraatlikus ühiskonnas, avalik hüve, mida see ühiskonnale pakub, seisneb seetõttu osaliselt paradoksaalses vastuolus – toota korraga nii ideederikkust ja -ringlust kui ka sellest rikkusest parimate (või üksmeelele jõudmise võimalust pakkuvate) ideede ja arengusuundade väljasõelumist. Järgnev peatükk vaatleb seda teemat nelja nurga alt: kuidas aruteluruumi erinevad allruumid toimivad, kes neis osalevad, kuivõrd võimaldavad need uute ideede ja eksperditeadmise aruteluruumi sisenemist ning kuivõrd võimaldavad arutelud eri allruumide dialooge ning teatud ühisosa tekitamist või parimates lahendustes kokkuleppele jõudmist.

Eesti avalikku aruteluruumi luuakse eri meediumidega. Neid on nii klassikalisi – trükiajakirjandus ja ringhääling – kui ka suhteliselt uuemaid – ajakirjandusväljaannete või -kanalite veebikeskkonnad, sotsiaalmeediaplatvormid, meelsuskogukonnad või huvivaldkonnad oma uudiste ja arutelukeskkondadega internetis (nt äärmusparempoolsete, alternatiivsete ravivõtete pooldajate või investeerimishuviliste veebikeskkonnad). Kõigil neil meediumidel ja nende allkeskkondadel on omad sisemised organiseerumispõhimõtted, millega korraldatakse seda, kes, millal ja mis ulatuses sõna saavad. Ajakirjanduslikel institutsioonidel on nimetatud reeglid kõige läbimõeldumad ja kõige enam järgitud. Seoses veebi dünaamilise arenguga on aga ka ajakirjanduslikes keskkondades need reeglid viimasel paaril aastakümnel pidevalt muutunud. Oma roll on ka meediaturu kontsentreerumisel ning sellega seonduval eri meedialiikide koondumisel meediakontsernide sees.

```{block, type='blockquote-right'}
Aruteluruumi areng sõltub meediaturgude kahe suundumuse, killustumise ja koondumise tasakaalust.
```

Meediaturge on ikka iseloomustanud see, et suured ettevõtted on tõhusamad ja seega võimekamad kui väiksemad ning tulemuseks on alati olnud oligipoolsed turud, mida kontrollivad üksikud suured meediakontsernid. Võrgumeedia ajastul on see suundumus süvenenud. Eesti peavoolulist ehk ajakirjanduslike meediakanalite poolt loodud aruteluruumi korraldavad Eestis praegu neli suuremat nn meediamaja (Eesti Rahvusringhääling, Postimees Grupp, Ekspress Grupp ja Äripäev). Meediamajade sees aga üritatakse efektiivsust saavutada ka mastaabisäästu põhimõttega, eri kanalite ja väljaannete sisu ristkasutades ja -turundades. Selle käigus on tulnud üle vaadata mitu senist ajakirjanduseetikat ja aruteluruumi korraldamist puudutavat reeglit. Otseseid muutusi on tinginud näiteks meediaväljaannetele kuuluvad, kuid vähem kontrollitud kommentaariumid, samuti meediainstitutsioonide tegevus sotsiaalmeedias. Nende esiletõus on tähendanud toimetusliku kontrolli vähenemist aruteluruumi üle. Meediakontsernide sisemine koondumine on ühtlasi aidanud neutraliseerida Eesti aruteluruumide killustumist eri meedialiikide lõikes, näiteks koondavad kontsernide veebiportaalid (Postimees.ee ja Delfi.ee) pea kõigi kontserni väljaannete ja kanalite loodud sisu. Niisiis on killustumisele olemas ka vastasjõud – koondumine – ning ka aruteluruumi areng sõltub nende kahe vastandliku suundumuse tasakaalust.

### Artiklite kokkuvõte {- .chapter4_section}

Järgnevalt võtan kokku ja seostan aruteluruumi peatüki artiklite põhisõnumid ehk Eesti meedia- ja kommunikatsiooniuurijate viimaste aastate uuringutulemused Eesti aruteluruumi arengu kohta. Jälgin eraldi kahte peamist meediatüüpi – toimetusliku kontrolliga ajakirjandust ning ilma toimetusliku kontrollita sotsiaalmeediat.

Osalust toimetusliku kontrollita võrgumeedias, sealhulgas sotsiaalmeedias, analüüsivad siinses peatükis Andreas Ventsel ja Mari-Liis Madisson oma artiklis ühiskondlik-poliitilisest kommunikatsioonist sotsiaalmeedias ning Veronika Kalmus ja Andra Siibak artiklis Eesti noorte osalusest virtuaalses aruteluruumis. Mõlemad artiklid osutavad võrgumeedias aset leidva kommunikatsiooni riskidele. Kui interneti algusajal omistati sellele oluline demokratiseeriv võime ning ka sotsiaalmeedias (eelkõige kasutajate täisnimesid kasutavas Facebookis) nähti ratsionaalse demokraatliku debati võimestajat, on nii Eesti kui ka muu maailma internetikommunikatsiooni uurijad viimastel aastatel osutanud pigem probleemidele. Ventsel ja Madisson näitavad, et avalike teemade arutamisel võrgumeedias on toimunud liikumine argumentatsiooni lihtsustumise suunas, suhtluses valdavad kiiresti mõistetavad ja tugeva emotsionaalse laenguga sõnumid.
```{block, type='blockquote-left'}
Afektiivse kommunikatsiooni funktsioon on aktuaalse ühiskondliku arengu esmane sildistamine, et väljendada mingite aspektide olulisust teatud sündmuste või nähtuste mõtestamisel.
```
Olulise nüüdisaegse autorina on Zizi Papacharissi võtnud sotsiaalmeedia kontekstis kasutusele afektiivse kommunikatsiooni mõiste ([Papacharissi 2016](#Papacharissi2016)). See viitabki puhkudele, kus lühikeste ja vahetute postituste mõjul kujuneb teatud aktuaalseid teemasid vormiv tunnetuslik atmosfäär ning käsitletavate teemade pakilisuse ühine tajumine. Afektiivse kommunikatsiooni funktsioon on aktuaalse ühiskondliku arengu esmane sildistamine, et väljendada mingite aspektide olulisust teatud sündmuste või nähtuste mõtestamisel. Selline kooskogemine on oluline kriiside aegu, mil sotsiaalmeediat võidakse kasutada kollektiivseks mure või ärritatuse näitamiseks ning esmaste seisukohtade väljendamiseks. Nii kriisiolukordades kui ka muul ajal seondub afektiivse kommunikatsiooniga ka sotsiaalmeedia omadus avaldada emotsioone, mis muidu jääksid allasurutuks. Suhteliselt tõenäolisemad on ka teisi halvustavad seisukohavõtud, eelarvamuslikkus või koguni vihakõne ([Tiidenberg 2017](#Tiidenberg2017)). Vihakõne all peame siinkohal silmas arvamusväljendusi, millega inimesi ähvardatakse, solvatakse või alandatakse mitte nende isikuomaduste, vaid grupikuuluvuse põhjal, näiteks kuulumine rassilisse, etnilisse, usulisse, puude või seksuaalse sättumusega seonduvasse gruppi.

Sotsiaalmeedia ja muude veebifoorumite eripäraks on, et need on võimaldanud märkimisväärselt mitmekesistada avalikke aruteluruume. Need keskkonnad võivad olla seotud ajakirjanduse loodud aruteluruumiga, kus teemasid vahendavad n-ö tavapärased arvamusliidrid (ajakirjanikud, poliitikud, teadlased, eksperdid). Kuid need võivad olla ka täiesti eraldiseisvad, kui neis on kesksel kohal kas ajakirjanduses ignoreeritud isikud või vaid sotsiaalmeedias oma mõju saavutanud inimesed (nt *youtuber*’id, Instagrami-kuulsused, Twitteri või Facebooki mikroblogijad jms), kes on suutnud eripärase sisu ja stiiliga endale suurema jälgijaskonna tekitada. Alternatiivsete arutelukeskkondade puhul nähakse aga riskikohana nende suhtelist suletust – arutelus ei osale mitte ainult suhteliselt piiratud ring osavõtjaid, vaid ka arutelude aines, nende ideoloogiline alus ja infoallikad jäävad üheülbaliseks. Sellised keskkonnad kinnistavad olemasolevaid arusaamu ja väärtusi, enamik neis esitatavast toetab osaliste juba väljakujunenud maailmapilti. Infosse, mis senistest arusaamadest lahkneb, suhtutakse sagedasti kui kahtlasesse või süvenemist mitteväärivasse. Niisugust suhtlemist on nimetatud kajakambri efektiks. Kui selliseid ruume on rohkelt, toob see kaasa ühiskonna laiema sisemise polariseerumise ([Madisson ja Ventsel 2016](#Madisson2016)).

```{block, type='blockquote-right'}
Vaid väga väike osa ühiskonnast (eri uuringute kohaselt 4–5%) piirdub oma meediatarbimises ja infootsingutes vaid üksikute keskkondadega.
```

Viimastel aastatel on välisuurijad ([Dutton jt 2017](#Dutton2017)) näidanud, et kajakambrite mõju ei ole ühiskonnas nii suur, kui vahepeal kardetud. Vaid väga väike osa ühiskonnast (eri uuringute kohaselt 4–5%) piirdub oma meediatarbimises ja infootsingutes vaid üksikute keskkondadega. Enamik inimesi puutub oma igapäevaelus kokku siiski üsna mitmekesise meediasisu spektriga, samuti kasutab suurem osa internetikasutajaid nüüdseks oskuslikult ka otsimootoreid, mis toovad inimesteni erilaadset informatsiooni. Suletud või poolsuletud ja afektiivsete aruteluruumide kaudsem probleemne kaasnähe on aga sellest hoolimata nende vastandumist ja polariseerumist tootev loogika. Seejuures ei vastanduta ainult teistsuguste vaadetega gruppidele, vaid ka meediainstitutsioonidele ja nende loodud arutelukeskkondadele, samuti institutsionaalselt tunnustatud asjatundjatele.

```{block, type='blockquote-left'}
Eestis puudub mehhanism, mis otseselt motiveeriks teadlasi avalikes aruteludes osalema
```

Toimetusliku kontrolliga meedia kohta saame lugeda Ragne Kõuts-Klemmi artiklist, et afektiivne kommunikatsioon on valdav ka ajalehtede kommentaariumides. Kommenteeritakse enam seda, mis on ärritav ja polariseeriv. Ka neist, enamasti siiski modereeritud keskkondadest võivad seetõttu saada kergelt vihakõne eskaleerumise kohad. Samal ajal saame Kõuts-Klemmi artiklist teada, et arvamusartiklite vormis saab ajalehtedes või nende veebikülgedel sõna siiski küllaltki kitsas ring inimesi – tuntud isikud ja need, kes on omandanud arvamusžanri võtted. Positiivseks tuleb pidada asjaolu, et arvamuskülgedel saavad rohkelt sõna ka eksperdid ja teadlased – Eesti ajalehtede arvamusküljed on „teaduse usku“. Siiski on osalemine ühiskondlikus debatis teadlastele tihti üksjagu rusuv. Arko Olesk näitab oma artiklis, kuidas Eestis puudub praegu mehhanism, mis otseselt motiveeriks teadlasi avalikes aruteludes osalema. Enamik teeb seda kodanikuaktiivsusest. Nii Olesk kui ka Kõuts-Klemm näitavad, kuidas keerulisemate ja teaduslikku asjatundlikkust vajavate käsitluste puhul võib meedia teemale n-ö alla jääda, keskendudes pigem kaasnevale konfliktile kui selle taga olevate faktide ja argumentide kaalumisele. Meedia võib teadlaskonna erimeelsusi naeruvääristada, vastuoluliste teemade puhul peab ekspert arvestama rünnakutega tema asjatundlikkuse vastu ja diskussiooni ideoloogilise tasalülitamisega, eksperditeadmiste tühistamisega. Sellised kogemused võivad olla eksperdile frustreerivad ja vähendada huvi aruteluruumis kaasa lüüa.

Eelnevaga seotud tähelepanuväärne areng, mida uurivad oma artiklis Veronika Kalmus ja Andra Siibak, on kasvava põlvkonna ehk noorte ettevaatlikkus eelkirjeldatud kas afektiivse või meediaväljaannete puhul tihti hierarhilise arutelruumi suhtes. Kuigi noorteni jõuavad uudised ja ühiskondlik keskustelu pigem sotsiaalmeedia kaudu kui otse ajakirjandust tarbides, usaldavad nad uudisteallikana meediaväljaandeid siiski enam. Virtuaalse aruteluruumi suhtes on nad kriitilised, nähes selles puuduvat viisakat ja argumenteeritud suhtluskultuuri. Seepärast eelistatakse virtuaalse aruteluruumi asemel pigem silmast silma suhtlust ning mõne konkreetse ühiskondliku valupunktiga otseselt, käsi külge pannes tegelemist.

```{block, type='blockquote-right'}
Iseseisvaks jäänud väljaanded otsivad püsimajäämiseks kõrvaltegevusi, mis on vähendanud nende sõltumatust kohalikest võimukandjatest.
```

Toimetusliku kontrolliga meedia ühe suurema probleemikohana, mis puudutab ka Eesti ruumilist arengut, tuleb aga esile tuua maakondliku ja väikekohtade ajakirjanduse keerukat olukorda. Sellele osutas 2019. aasta alguses Tartu ja Tallinna meediauurijate tehtud ühisuuring ([Kõuts-Klemm jt 2019](#Kõuts-Klemm2019)). Ajakirjanduse üks väljakujunenud tuluallikaid on reklaam, kuid Eesti meediaettevõtete sissetulek reklaamist on rahvusvaheliste digiplatvormide siinse reklaamivahendustegevuse tõttu aina piiratum. Lisaks, kuivõrd suurem osa majandustegevusest on koondunud suurlinnadesse, on maakonna või valla reklaamiturg kahanenud sedavõrd, et seab ohtu kvaliteetse kohaliku ajakirjanduse kestmise. Suure osa maakondlikest ajakirjandusväljaannetest on Eesti suuremad meediamajad juba üles ostnud ja oma tegevusse lõiminud ning kontsernisisest mastaabisäästu püüeldes on kohaliku väljaande tegevusulatus tihtipeale kahanenud. Iseseisvaks jäänud väljaanded otsivad püsimajäämiseks kõrvaltegevusi, mis on tihtipeale vähendanud nende sõltumatust kohalikest võimukandjatest. Kartes kaotada koostööpartnereid (nt omavalitsus, reklaamitellijad) võivad kohalikud ajakirjandusettevõtted jätta täitmata ülesande jälgida kriitiliselt majandusliku ja poliitilise võimu teostamist. Kohalikud omavalitsused, kes rahastavad omaenda tasuta jagatavaid väljaandeid ja pahatihti müüvad neisse isegi reklaami, raskendavad omakorda kohaliku sõltumatu meedia püsimajäämist. Kõik see ohustab ka kohaliku aruteluruumi toimimist. Kui puuduvad sõltumatud institutsioonid, mis kohalikku arutelu veavad ja edendavad, vähendab see ka võimalust, et nende arutelude abil saaks konsensuslikult setitada kohalikke arengueesmärke ning et toimiv paikkondlik infovahetus looks väiksemate kohtade elanikele ja ettevõtetele igapäevaelus uusi võimalusi.

### Kuidas edasi? {- .chapter4_section}

Eelneva võib kokku võtta järeldusega, et Eesti vahendatud aruteluruum ei toimi ideaalselt. Kui ajakirjandusliku meedia loodud aruteluruumi probleemid – keskendatus konfliktidele, nähtuste lihtsustamine, kõnejärje andmisel tuntud ja žanrivõtted omandanud isikute eelistamine – on vanad, siis võrgumeediaga on kaasnenud aruteluruumi osaline killustumine ning uutes ruumides kohati silmatorkav ühiskondlikust dialoogist keeldumine, asjatundlikkusel põhineva autoriteetsuse mittetunnustamine ning üldiselt leviv afektiivne kõnepruuk on uued. Selle tulemuseks omakorda on aga osa ühiskonnagruppide, sealhulgas noorte eemalehoidmine ühiskondlikust avalikust arutelust. Need probleemid ei ole Eestile ainuomased. Selliseid suundumisi kirjeldatakse mitmel pool maailmas, seda enam, et kommunikatsiooniks kasutatavad platvormid on üldjuhul samad. Kuivõrd võrgukeskkondadega kaasnevate riskide eest demokraatiale nähakse vastutavana suuri sotsiaalmeediaplatvorme, on Euroopa Liit ja suuremad riigid asunud neilt otsustavalt nõudma nii võltsuudiste leviku peatamist kui ka selliste keskkondade sulgemist, kus vihakõne või väärinfo levitamine on regulaarne. Arvestades, et ka Eesti aruteluruumi toimimine ja ühiskondliku dialoogi kvaliteet sõltub rahvusvahelistest platvormidest, peab Eesti edaspidi tähelepanelikult ja nõudlikult osalema Euroopa Liidu kui võimeka rahvusvaheliste turgude reguleerija teemakohases töös.

```{block, type='blockquote-left'}
Eesti kohalikud meediaorganisatsioonid on aastaid kaotamas turupositsioone (sh reklaamiraha) üleilmsetele platvormidele.
```

Rahvusvahelises regulatiivses töös, kuid samuti ka Eesti meediapoliitika arendamisel tuleb silmas pidada sedagi, et Eesti kohalikud meediaorganisatsioonid on juba aastaid kaotamas turupositsioone (sh reklaamiraha) üleilmsetele platvormidele. On oluline suunata osa sellest rahast tagasi, näiteks nimetatud platvorme maksustades, et siinset ajakirjandust Eesti aruteluruumi kujundamisel võimestada. Erilist tähelepanu tuleb seejuures pöörata just maakondlikule ja kohalikule ajakirjandusele, mis on kõige haavatavamas seisus. Et viimaste tööst sõltub otseselt avaliku aruteluruumi kvaliteet väljaspool suuremaid linnu, on neil mõju ka laiemale Eesti tasakaalustatud ruumilisele arengule. Eesti maakondlikku ja kohalikku ajakirjandust ei saa aga võimestada üksnes otsetoetuste või subsiidiumidega, vaid parandada tuleb laiemat koostööd Eesti meedia- ja kultuuriasutuste ning avaliku sektori vahel. Oluline arengusuund on seejuures andmete, eriti avaandmete jagamine, kuid kindlasti ka otsesem püüd üksteise tegevusi võimendada. Muu hulgas tuleb oluliselt parandada Eesti Rahvusringhäälingu tuge kohalikule ajakirjandusele ja väikekohtade aruteluruumile. Näiteks tuleks tihendada korrespondentide võrku, tagada suurem kohalolek eriti Lõuna-Eestis ning pakkuda kohalikele väljaannetele ja kanalitele ka võrgukeskkondade arendamiseks teenuseid ja platvormi.

```{block, type='blockquote-right'}
Erilist tähelepanu tuleb pöörata maakondlikule ja kohalikule ajakirjandusele, mis on kõige haavatavamas seisus.
```

Eesti laiema aruteluruumi arenguks peaks Eesti ajakirjandusele olema kriitiliselt tähtis eri laadi asjatundlikkuse kaasamine avalikku arutellu. Eesti ajakirjandus annab küll teadlastele ja teistele ekspertidele sõna, kuid teemade käsitlus ei pruugi samal ajal olla tasakaalukas. Meediakanalid peavad leidma viisi, kuidas keerukat tõendust vajavaid teemasid avalikkusele esitleda nii, et arutelu kujuneks vähem emotsionaalseks ja rohkem dialoogiliseks, mõistmist ning parimat lahendust otsivaks. Ka teadusasutused ja teaduspoliitika suunajad peavad leidma paremaid võimalusi, kuidas motiveerida teadlasi avalikes aruteludes osalema, ning koolitama neid seda tegema mõjusal, ühiskonna üldist teadlikkust suurendaval ja arutelu edendaval viisil.

Nagu siinse sissejuhatuse alguses tõdetud – laiem aruteluruum peab võimaldama nii alternatiivsete ja eripäraste ideede ehk mitmekesisuse esile kerkimist ning küpsemist kui ka üldist ühiskondliku dialoogi ja üksmeele otsimist. Ajakirjanduse kui aruteluruumi kujundaja perspektiivist peaks see tähendama esiteks spetsiifilisemate temaatiliste aruteluruumide loomist või nende otsinguid (nt teadusvaldkondade foorumid või muud pädevad arutelukeskkonnad). Teiseks tuleks võimaldada nende ruumide vahelist dialoogi, vahendada olulisi ideid ja kvaliteetset teadmust laiale elanikkonnale, kaasates kodanikke arutellu modereeritud positiivsete hõivamisvormide kaudu. Selline eri teadmusruumide ühendamine on klassikalise rahvuslike innovatsioonisüsteemide teooria ([Lundvall 2010](#Lundvall2010)) põhjal esmane eeldus dünaamilise aruteluruumi arenguks, mis on võimeline pidevalt sünteesima uusi ideid ning erinevaid alternatiivseid võimalusi kas riskide maandamiseks või uute arenguvõimaluste realiseerimiseks. Kui tavaliselt rõhutatakse selliste rahvuslike innovatsioonisüsteemide tekkes ülikoolide, ettevõtluse ja avaliku sektori hea koostöö olulisust, siis tänapäeva võrguajastul tuleb hakata nägema ka kvaliteetse ajakirjanduse ja meediasektori kui laiema ühiskondliku mõtte- ja ideevahetuse kureerija olulisust ([Ibrus 2019](#Ibrus2019)).

```{block, type='blockquote-left'}
Veebipõhise suhtluse riskide vältimine sõltub kahtlemata sellest, kuidas suureneb üldine teadlikkus neist riskidest.
```

Arutelukultuuri areng, aga eriti veebipõhise suhtluse riskide vältimine sõltub kahtlemata sellest, kuidas suureneb üldine teadlikkus neist riskidest. Intervjuud Eesti meediajuhtidega osutasid ([Kõuts-Klemm jt 2019](#Kõuts-Klemm2019)), et praegused noored on hoopis meedia- ja allikakriitilisemad kui vanem põlvkond. Noorte ettevaatlikkus tuli välja ka Kalmuse ja Siibaku käesoleva kogumiku artiklist. Niisiis võiks üks eesmärke olla laiendada koolides end tõestanud meediaharidusprogramme ka laiemale elanikkonnale. Selliste programmide eestvedajaks saaksid olla meediaorganisatsioonid ise kui arutelukultuuri kvaliteedist kriitiliselt huvitatud osapooled.

### Viidatud allikad {-.subreferences}

<p id="Dutton2017">Dutton, W. H., Reisdorf, B., Dubois, E., Blank, G. 2017. Social shaping of the politics of internet search and networking: moving beyond filter bubbles, echo chambers, and fake news. Quello Center Working Paper No 2944191. Lansing: Michigan State University.</p>

<p id="Ibrus2019">Ibrus, I. (ed.) 2019. Emergence of Cross-innovation Systems: Audiovisual Industries Co-innovating with Education, Health Care and Tourism. Bingley: Emerald.</p>

<p id="Kõuts-Klemm2019">Kõuts-Klemm, R., Harro-Loit, H., Ibrus, I., Ivask, S., Juurik, M., Jõesaar, A., Järvekülg, M., Kauber, S., Koorberg, V., Lassur, S., Loit, U., Tafel-Viia, K. 2019. Meediapoliitika olukorra ja arengusuundade uuring. Tartu, Tallinn: Tartu Ülikool, Tallinna Ülikool.</p>

<p id="Lundvall2010">Lundvall, B. Å. 2010. National Systems of Innovation: Toward a Theory of Innovation and Interactive Learning. London: Anthem Press. </p>

<p id="Madisson2016">Madisson, M., Ventsel, A. 2016. Autocommunicative meaning-making in online-communication of Estonian extreme right. – Sign Systems Studies, 44 (3), 326−354.</p>

<p id="Papacharissi2016">Papacharissi, Z. 2016. Affective publics and structures of storytelling: sentiment, events and mediality. – Information, Communication & Society, 19 (3), 307–324.</p>

<p id="Tiidenberg2017">Tiidenberg, K. 2017. Ihu ja hingega internetis. Tallinn: Tallinna Ülikooli Kirjastus.</p>
