## Ühiskondlik-poliitiline diskussioon digitaalses avalikus ruumis {.chapter_section .chapter4_section}

```{block, type='authors'}
<div class="author-links">**[Andreas Ventsel](#andreas-ventsel) ja [Mari-Liis Madisson](#mari-liis-madisson)**</div>
<div><a class="print-btn" href="print/EIA-2019-4.1.pdf"><i class="fa fa-file" aria-hidden="true"></i>Trükiversioon</a></div>
```

```{block, type='points'}
* Sotsiaalmeedia avalikus ruumis avaldatud sõnumitele ei kehti selged ajakirjanduse eetika- ja kvaliteedipõhimõtted nagu kutseliste ajakirjandusväljaannete puhul.
```

Eestis saavutasid aktiivsete meediakasutajate jälgitavates kanalites elektroonilised vahendid ülekaalu 2011. aastal. Käesolev artikkel keskendub avalikku sotsiaalmeediasuhtlust iseloomustavatele tähendusloome suundumustele ja nende rollile ühiskondlik-poliitiliste arutelude kujundamisel.

```{block, type='blockquote-right'}
Tähendusloome on protsess, mille vahendusel suhtluspartnerid püüavad üksteisest ja ümbritsevast maailmast aru saada, vestluskaaslast mõjutada ning mõningatel juhtudel teda lausa eksitada.
```

Meie eesmärk on näidata, millised tähendusloome suundumused viivad sotsiaalmeediasuhtluse sulgumiseni ja radikaliseerumiseni, millised aga demokraatlikuma avatud kommunikatsioonini. Osutame konkreetsetele näidetele ja uurimustele, mis aitavad sotsiaalmeedia arutelude tunnuseid ning tähendusloome tüüpe kaardistada. Eestis on seni avaldatud vähe (sotsiaal)meedia tähendusloome eripäradele pühendatud kvalitatiivseid uuringuid. Samuti on oluline tähele panna, et digitaalne avalik ruum on märksa laiem kui sotsiaalmeedia, ent just viimases saavad kokku väga mitmesugused kanalid ja infosfäärid ning see on üks peamisi kohti, kus kodanikud avalike teemade käsitlemisel osalevad. On kujunenud teabekeskkond – digitaalne avalik ruum, kus interaktiivsete võrku ühendatud seadmete kasutajad saavad nii teiste loodud infot tarbida kui ka selle loomises osaleda. Teaduskirjanduses on osutatud teabekeskkonna tekkimise probleemidele. Ühena neist nimetatakse asjaolu, et avalike teemade arutamisel digitaalses meedias on toimunud jõuline liikumine lihtsustumise ja personaliseerumise suunas.

```{block, type='blockquote-left'}
Digitaalne avalik ruum on märksa laiem kui sotsiaalmeedia, ent just viimases saavad kokku väga mitmesugused kanalid ja infosfäärid ning see on üks peamisi kohti, kus kodanikud avalike teemade käsitlemisel osalevad.
```

Tavapäraselt on ühiskondlik-poliitiline arutelu jõudnud laiema auditooriumini ajakirjanduse vahendusel, kus toimetused valivad välja mitmekülgse taustaga esinejad ning püüavad tagada teemas püsimise ja normikohase väitluse. Sotsiaalmeediaajastul on avalike arutelupindade hulk märkimisväärselt mitmekesistunud ning võimalikult suure auditooriumini jõudmiseks ei pea kõnelejad enam ajakirjanduse vahendavast rollist sõltuma. Sotsiaalmeedias võivad avalike teemade vahendajateks olla n-ö traditsioonilised arvamusliidrid (ajakirjanikud, poliitikud, teadlased, eksperdid), mitmesuguste ettevõtete või institutsioonide kontod, arutelugrupid, aga ka sotsiaalmeedia mõjuisikud (nt Youtube’i postitajad, Instagrami-kuulsused, Twitteri või Facebooki mikroblogijad jms), kes on suutnud sagedaste postituste, huviväärse sisu ning paeluva stiili tõttu endale suure jälgijaskonna tekitada. Sotsiaalmeedia vahendajad koondavad konkreetsete teemadega seonduvat teavet ja jagavad sageli ka selle info tõlgendamiseks suuniseid, lisaks pakuvad nende leheküljed võimalust postitatud sisu üle nii vahendaja enda kui ka tema auditooriumiga arutleda. Uuringud on näidanud, et eriti noorem publik eelistab avalike teemadega kursisolekuks peamise kanalina sotsiaalmeediat ega pea ajakirjandusliku töö tulemusena valminud tekste enam põhiliseks ja eelistatumaks uudise liigiks ([Vihalemm ja Kõuts-Klemm 2017, lk 256, 258](#Vihalemm2017); [Opermann 2018](#Opermann2018)). Sarnast suundumust on täheldatud ka muu maailma noorte hulgas ([Newman jt 2017](#Newman2017)). Sotsiaalmeedia vahendajatega seonduv peamine risk seisneb selles, et neil on teatud teemade ühiskondliku tähenduse kujunemise suhtes suur võim, kuid nende eesmärgid ja tegutsemispõhimõtted jäävad auditooriumile sageli varjatuks.

Uurimistöö on näidanud, et Venemaa infosõja sõdurid, kelle eesmärk on eksitavaid seoseid külvata, konflikte õhutada ja NATO usaldusväärsust õõnestada, on iseäranis ohtlikud, kui neil õnnestub saavutada populaarse vahendaja või sotsiaalmeedia mõjuisiku staatus ([Jantunen 2018](#Jantunen2018); [Nissen 2015](#Nissen2015)). Nende tegevuse põhisihiks on kujundada avalikku arvamust viisil, mis võimaldaks inforünnakute organiseerijal oma poliitilis-majanduslikke eesmärke saavutada. Niisuguses õõnestustegevus kasutatakse väga emotsionaalseid ja/või vastuolulisi teemasid, kombineerides sihtgrupile tuttavaid sündmusi ning strateegiliselt kujundatud lugusid. Viimaste usaldusväärseks muutmiseks kasutatakse näiteks võltsitud tegelasi (vahel näitlejate etendatud karakterid), kunstlikult tekitatud sotsiaalmeediaaktiivsust (ostetud laigid ja kommentaarid), olematuid teadusallikaid, konflikti õhutavaid vandenõuteooriaid ja vasturääkivusi.

### Sotsiaalmeedia lubavused soodustavad emotsioonipõhist suhtlust {-.chapter4_section}

Sotsiaalmeedia aruteluruumi eripärade käsitlemiseks on oluline mõista sotsiaalmeediaplatvormide tehnilisi ja sotsiaalseid võimalusi. Sotsiaalmeedia pakutavate võimaluste ehk lubavuste tõttu on teatud käitumis- või kasutamisviisid kasutajale mugavamad, iseenesestmõistetavamad ja seega tõenäolisemad kui mõned muud ([Tiidenberg 2017, lk 21](#2Tiidenberg2017)). Sotsiaalmeedia olulisemate lubavustena on nimetatud näiteks jäävust ehk sotsiaalmeedias esitatu automaatset säilitamist ja arhiveerimist, kopeeritavust ehk tekstide hõlpsat paljundatavust ning otsitavust ehk loodud sisu kajastumist otsingumootorites ([samas, lk 67](#2Tiidenberg2017)). Lisaks on sotsiaalmeedia lubavustena esile toodud anonüümsuse- või nähtamatusetunnet, mis innustab inimesi oma kaemust väga avameelselt jagama. Nii avatakse sotsiaalmeedias sageli emotsioone, mis jääksid muidu allasurutuks, sellega seoses on tõenäolisemad ka teisi halvustavad seisukohavõtud, eelarvamuslikkus või koguni vihakõne ([samas, lk 58](#2Tiidenberg2017)).

```{block, type='blockquote-left'}
Sotsiaalmeedia lubavused soodustavad selliste avalike kogukondade tekkimist, mida iseloomustavad formeerumise kiirus, geograafiline hajutatus, anonüümsus ja emotsioonipõhisus.
```
Reaktsioonide, kopeerimis- ja jagamisfunktsiooni populaarsust seostatakse sotsiaalmeedia aruteluruumi emotsioonipõhiseks ja vähem argumenteerituks muutumisega. Nende lubavuste tõttu on sotsiaalmeedia diskussioonides pretsedenditult tähtis roll ühenduses oleku, kaasatuse ning tekstide kooskogemise tunde võimendamisel. Kommunikatsiooniuurija Zizi Papacharissi uuris koos oma uurimisrühmaga miljoneid Occupy Wall Streeti ja araabia kevadega (iseäranis Egiptusega) seotud Twitteri-säutse ning võttis taolise suhtluse eripära kirjeldamiseks kasutusele afektiivse jutustamise (ingl *affective storytelling*) mõiste ([Papacharissi 2016](#Papacharissi2016)). Üks olulisemaid järeldusi on, et kiirete reaktsioonide või üldjuhul üsna lühikestest postitustest koosnevate afektiivsete sotsiaalmeedia lõimede vahendusel kujuneb teatud teemasid vormiv tunnetuslik õhkkond ning nende teemade pakilisuse ja olulisuse ühine tajumine, ent samas ka algeline viis nende kollektiivse tähenduse esmaseks sildistamiseks  (samas, lk 311). Niisuguse afektiivse kommunikatsiooni aluseks on ühine äratundmine, et mingid aspektid on teatud sündmuste või nähtuste mõtestamisel olulised, ehkki need ei liigendu veel selgelt eristuvateks tähendusüksusteks. Afektiivne kooskogemise tunne on sotsiaalmeedias iseäranis tõenäoline kriiside, katastroofide ja konfliktide ajal ehk puhkudel, kui sotsiaalmeediat kasutatakse kollektiivse mure ja ärritatuse väljendamiseks.

### Interneti kasutamine Eestis {-.chapter4_section}

„Mina. Maailm. Meedia“ (MeeMa) uuringu andmetel on Eestis alates 1990. aastate lõpust, eriti aga pärast sajandivahetust internetikasutus väga kiiresti kasvanud. Uuringus kasutatud Kantar Emori andmetel tõusis internetikasutus 15–74-aastase elanikkonna hulgas 28%-lt 2000. aastal 83%-ni 2014. aastal ([Vihalemm ja Kõuts-Klemm 2017, lk 263](#Vihalemm2017)). Eesti näitajad on võrreldavad USA ja Suurbritanniaga, kus internetikasutajaid on täiskasvanud elanikkonnas 87% ([samas, lk 252](#Vihalemm2017)). Nagu kinnitavad Emori ja MeeMa 2014. aasta uuringu tulemused, ei ole internet kujunenud kõige populaarsemaks meediumiks Eestis üksnes nooremaealiste hulgas, vaid on samavõrra mõjutanud traditsioonilise meedia kasutamist ka teistes vanuserühmades ([samas, lk 264](#Vihalemm2017)). Seejuures ei ole internetikasutamises haridustaseme ja soopõhised erinevused nii suured kui erinevused internetikasutajate vanusegruppide vahel – nooremas vanusegrupis (15–19-aastased) oli kasutajaid 100%, keskeas vanuserühmas (40–49-aastased) 75% ja pensionieas inimeste hulgas 54%. Samuti ei ole internetikasutamises olulisi erinevusi eesti- ja venekeelsete inimeste hulgas ([samas, lk 264](#Vihalemm2017)).

Uue sajandi esimese kümnendi lõpus sai alguse ka sotsiaalmeedia populaarsuse plahvatuslik kasv ning kujunemine nii avaliku kui ka privaatse inforuumi keskmeks. Kultuuriministeeriumi tellitud uuringu ([Kaldur jt 2017](#Kaldur2017)) järgi on nii eesti- kui ka venekeelse elanikkonna seas populaarne platvorm Facebook, mida kasutab aktiivselt 56% eestlastest (noortest koguni 90%) ning 43% venekeelsest elanikkonnast. Venekeelse elanikkonna hulgas on peale Facebooki populaarsed veel venekeelsed platvormid Odnoklassniki (33%) ja VKontakte (26%). Eesti inimesed on harjunud kaasaskantavate interaktiivsete ekraanide vahendusel ühiselu puudutavat teavet, päevauudiseid ja poliitilisi debatte jälgima, ent ka aeg-ajalt aruteludes osalema. Seejuures võime näha, et huvi uudiste vastu on elanikkonnas endiselt üpris suur ning muutunud on vaid kanalid, mille kaudu uudiseid jälgitakse – n-ö traditsiooniliste meediakanalite kahjuks. Ligikaudu veerand MeeMa 2014. aasta küsitlusele vastanutest väidab, et nad on loobunud interneti tõttu ajalehtede lugemisest, kümnendik ka tele- ja raadiouudiste jälgimisest traditsioonilisel viisil ([Vihalemm ja Kõuts-Klemm 2017, lk 254](#Vihalemm2017)). MeeMa uuringu järgi on esile kerkinud kasutajatüüp, kelle meediarepertuaar piirneb eelkõige sotsiaalmeediaga ning väga vähesel määral internetiportaalide ja veebilehtedega.

*Ilmselt domineerib selle tüübi huvide seas suhtlus- ja meelelahutushuvi, samas kui huvi uudiste ja arutluste vastu on vähene. Võib väita, et esimese [2004] ja viimase „Mina. Maailm. Meedia“ [2017] on toimunud oluline murrang elanikkonna meediaeelistustes: ligi pooled eestlastest eelistavad meediakasutuseks internetikeskkonda. See omakorda tähendab auditooriumi veelgi ulatuslikumat fragmenteerumist ([Vihalemm ja Kõuts-Klemm 2017, lk 274](#Vihalemm2017)).*

Sotsiaalmeediasse on tekkinud arvukalt avalikke (mitmesugused lehed ja kõigile registreeritud platvormikasutajatele kättesaadavad grupid) ja poolavalikke diskusioonipindu (grupid, kuhu pääseb administraatori heakskiidul), mille keskmes on kas maailmavaateliste (nt Virginia Woolf sind ei karda!, EKRE Sõprade Klubi) või päevakajaliste ühiskondlike teemade arutamine (nt Aitäh, aga minu traditsiooniline perekond ei vaja kaitset, Eesti Metsa Abiks, EI PAGULASMASSIDELE). Tõsi, avalike teemade (ühiselu puudutavate uudiste, poliitiliste debattide jne) vaagimine ei ole digitaalse meediakasutuse põhiline ja ainuke tulipunkt. Selle kõrval suheldakse sõprade-tuttavate ringiga ning luuakse ja tarbitakse meelelahutuslikku sisu.

### Suletud tähendusloome tekitab polariseerumist {-.chapter4_section}


```{block, type='blockquote-right'}
Suletud tähendusloomet iseloomustab halvustav ja tõrjuv suhtumine oponentidesse ning muudesse võimalikesse vaatepunktidesse.
```
Eelkirjeldatud sotsiaalmeediasuhtluse analüüsimine avatud ja suletud tähendusloome raamistikus aitab mõista tegureid, mis viivad kommunikatsiooni kapseldumiseni või soodustavad dialoogi. Mõistame suletud tähendusloomena suhtlemist, mis toetub eelkõige seostele, mida potentsiaalne saaja juba eelnevalt teab, ning mis pigem väldib alternatiivseid vaatepunkte ([Madisson ja Ventsel 2016](#Madisson-Ventsel2016)). Sotsiaalmeedia arutelukliima peamise murekohana nähaksegi selle takerdumist stereotüüpidesse ja liiga üheülbaliste arvamuste vahetusse. Sotsiaalmeedias eelistatakse info- ja kommunikatsiooniruumi, mis olemasolevaid arusaamu ja väärtusi kinnistab või vähemalt varasemate veendumustega ilma kimbatust ja vastuolusid tekitamata haakub. Infosse, mis olemasolevatest arusaamadest lahkneb, suhtutakse kui ebaolulisse ning mitte süvenemist väärivasse. Niisugust suhtlemist on nimetatud kajakambri efektiks, mis kasvatab ja ühtlustab kogukondlikku mälu ja kus sarnaste vestluspartneritega suheldes eelarvamused ning ühised seisukohad kinnistuvad ja polariseeruvad ([samas](#Madisson-Ventsel2016)).

```{block, type='blockquote-left'}
Kajakambri efekt iseloomustab suhtlusolukorda, kus sarnaste vestluspartneritega suheldes eelarvamused ja ühised seisukohad kinnistuvad ja polariseeruvad.
```

Sotsiaalmeedia kajakambrisuhtlusele on iseloomulik oponentide halvustav ja karikatuurne kujutamine, mis omakorda vähendab nendega dialoogi astumise võimalust. Tähendusloome seisukohalt on kajakambrisuhtluse tulemus suuresti etteennustatav, sest selle aluseks on teravat vastandumist tekitav antiteetiline loogika. See jagab maailma kaheks vastandlikuks (binaarseks) osaks: moraalseks ja ebamoraalseks, kasulikuks ja kahjulikuks, sõpradeks ja vaenlasteks jne. Kajakambriefekt ilmneb sageli sotsiaalmeediaaruteludes, mis kujunevad konfliktsete ühiselu puudutavate teemade ümber, olgu nendeks näiteks puidurafineerimistehase rajamise plaan, metsanduspoliitika või ränderaamistik ([Olesk, käesolev kogumik](#ekspertide-roll-ja-staatus-ühiskondlikes-meediaaruteludes)). Eriti tugevalt avaldub kajakambriefekt suhtluses, mis koondab äärmuslike poliitiliste vaadetega vestlejaid. Näiteks Eesti paremäärmuslikele blogidele keskendunud kvalitatiivsest uurimusest ([Madisson 2016](#2Madisson2016)) selgus, et sealne suletud tähendusloome ei võimalda enamasti väärtuste ja normide suhtelisuse tajumist ega tunnusta tõlgendusteede ja vaatepunktide paljusust. Uuritud 2015.–2016. aasta Euroopa rändekriisile keskenduvates postitustes tuli seda laadi tähendusloome jõuliselt esile. Nii vastandati aatelised, õiglased, tasakaalukad, võõrale propagandale mittealluvad rahvuslikud põliseestlased valelikele, kasuahnetele, kahepalgelistele, ebaloomulikele, rumalatele ja hüsteerilist retoorikat harrastavatele gruppidele ning ka korruptiivse meedia- ja haridussüsteemi tõttu n-ö ajupestud tavakodanike massidele ([samas](#2Madisson2016)). Ka Eesti Konservatiivse Rahvaerakonna ja selle juhtfiguuride 2014.–2016. avalikku sotsiaalmeediasisu käsitlenud uurimus täheldas märkimisväärset antiteetilise tähendusloome osakaalu. Näiteks positsioneeris erakonna sotsiaalmeediaretoorika kõikvõimalikke oponente, näiteks naiste ja seksuaalvähemuse õiguste eest seisjaid, vene rahvuse esindajaid, teiste erakondade juhtpoliitikuid, Eesti suuremaid meediaväljaandeid, aga ka mitmeid ühiskonnateoreetikuid (nt Herbert Marcuset ja Theodor Adornot) ohtlike vaenlastena ([Kasekamp jt 2018](#Kasekamp2018)).

Sotsiaalmeediasuhtlus on oma olemuselt hübriidne, sest see põimib kommertshuvisid teenivatel platvormidel (nt Facebook ja Twitter) sageli kokku nii avaliku, privaatse kui ka alternatiivse teabesfääri. Ometi kipuvad sotsiaalmeedia gruppides osalevad inimesed sealset inforuumi väärtustama just põhjusel, et seda tajutakse olevat võrsunud rohujuuretasandilt või „inimeste endi seast“. Arutelugruppides, mida iseloomustab tugev kajakambriefekt ja polariseerumine, võib täheldada jõulist vastandumist juhtivatele meediaväljaannetele ning sageli ka võimuinstitutsioonidele. Taolistes aruteluruumides rõhutatakse rohujuuretasandi autoriteetsust, mis tähendab eelkõige usaldust mitteametliku teadmise vastu ehk tavade ja arusaamade vastu, mille loomise ja vahendamise puhul ei tajuta institutsionaalse sfääri, näiteks valitsuse, meediaettevõtete, haridusasutuste jms mõju ([Howard 2011, lk 7–10](#Howard2011)). Mingite teadmiste ja hoiakute tajumine rohujuuretasandilt võrsununa toimib kui väärtuskriteerium, kus usaldusväärsus ei tulene mitte niivõrd väidete ja argumenteerimise kvaliteedist, kuivõrd ennekõike vastandumisest peavoolule. Taolisele suundumusele on osutanud Andra Siibaku ja Anu Masso 2018. aasta kvalitatiivne uurimus, mis põhines intervjuudel, kus pagulasvastaste Facebooki grupi „EI Pagulastele / Estonians against refugee quotas“ liikmed avasid põhjusi, miks nad aktiivselt seda gruppi külastavad. Peamiselt tulid välja eliidivastased hoiakud, sealhulgas tugev usaldamatus nii suuremate meediakanalite kui ka erakondade vastu. Intervjueeritavad jagasid seisukohta, et pagulasvastane Facebooki grupp on ainus kanal, kust immigratsiooniteemal kallutamata infot hankida. Vastajad väärtustasid isiklikke lugusid, kus „inimesed nagu nemad ise“ vahendasid oma (üldjuhul negatiivseid) kogemusi väidetavate immigrantidega ([samas, lk 317–318](#Siibak2018)). Uurimuse järeldusena märgivad autorid ([samas, lk 318–319](#Siibak2018)), et pagulasvastane grupp toimis kui kajakamber, mis võimendas ja ühtlustas massiimmigratsiooniga seotud eelarvamusi.

```{block, type='casebox'}
<h3>Suletud auditooriumiga suhtlusgrupid</h3>

Kajakambristunud poliitikateemaliste arutelugruppide kõrval on institutsionaalsele autoriteedile vastanduv tähendusloome levinud alternatiivmeditsiini valdkonna vestlustes. Eesti avalikkuses on enim kõneainet pakkunud suletud Facebooki grupp „MMS ja DMSO Eesti“, kus propageeriti MMSi kui „imelise mineraalilahuse“ ehk kloordioksiidi kasutamist mitmesuguste haiguste ennetamisel ja ravis. Kõnealune grupp koondas ligi 8000 kasutajat ning vastandus jõuliselt nii Eesti ametlikule meditsiinisüsteemile kui ka suurematele meediaväljaannetele, süüdistades viimaseid pahatahtlikus laimukampaanias ja vandenõus. Avaliku tähelepanu ning Terviseameti pöördumiste tõttu sulges Facebook 2018. aasta septembris selle grupi.
```

Kajakambrisuhtluse stereotüüpidel ja kordustel põhinevat infokasutust kompenseerib tugev kogukondliku sideme loomise võime. Suhtlemise sihiks on vestluspartneri tunnustamine/mittetunnustamine, tähtis roll on usaldusliku kontakti loomisel, mis põhineb grupisiseste normide kinnitamisel ja ühtlustunde tekitamisel. Lisaks tagab taoline suhtlus suure tõenäosusega motivatsiooni ja kindlustunde edasiseks kontaktideks, kuna „õigel“ viisil loodud teated tagavad positiivse tagasiside, mis annab omakorda hoogu edasiseks suhtluseks. Samal ajal võib sotsiaalsete suhete loomisele suunatud suhtlus olla kättesaadav vaid piiratud auditooriumile: näiteks võidakse grupiga liitumisel nõuda suhtlusgruppi kuuluvate liikmete soovitusi või reguleeritakse seda ankeedilaadse küsimustikuga. Uue liikme sobivuse üle otsustavad enamasti sotsiaalmeediagrupi valitud usaldusisikud ehk moderaatorid.

### Avatud tähendusloome kaasab eri osapooli {-.chapter4_section}

Nagu nimigi osutab, on avatud tähendusloome avatud uutele suhtluspartneritele ning alternatiivsetele vaatepunktidele. Avatud tähendusloome on suunatud eri seisukohtade sünteesimisele ning järgib ideaalis arutleva demokraatia tingimusi, mille kohaselt peaks suhtlemine olema:

1) vaba ehk ainult arutluse tulemused ja reeglid on siduvad;

2) mõistlik ehk rakendatakse ainult „parema argumendi jõudu“ ([Habermas 1998](#Habermas1998));

3) võrdsuse printsiibist lähtuv ehk kõigil on võrdne õigus kõnelda ja kritiseerida ja

4) konsensuslik ehk ideaalne arutelu seab sihiks ratsionaalselt motiveeritud üksmeele saavutamise suhtluspartnerite vahel ([Cohen 1989](#Cohen1989)).


```{block, type='blockquote-right'}
Ideaalis võimaldab avatud tähendusloome arutluses osalejatel ratsionaalselt motiveeritud üksmeeleni jõuda.
```

Ühiskondlik dialoog tähendab avalike teemade arutamist argumenteeritul ja eri huvigruppe võrdselt kaasaval viisil. Dialoogi oluliseks sihiks on suhtluspartnerite mõistmine ning kõiki osapooli arvestava seisukoha väljaarendamine. Vastupidiselt suletud tähendusloomele on dialoogilise ja avatud tähendusloome oluliseks kriteeriumiks suhtluspartnerite püüe leida ühist keelt, mille abil on võimalik arutleda ühiskondlikult olulistel teemadel. See avaldub kujukalt näiteks siis, kui üks vestluspartner palub teisel arusaamatud terminid lahti seletada või kui püütakse leppida kokku reeglites, millele dialoog üles ehitada. Asjaolu, et kommunikatsioonis osalejad pakuvad samast asjast rääkides erinevaid tõlgendusi, on loomulik. Avatud tähendusloomet iseloomustab kõnealuse teema, arutelu objekti piiride pidev täpsustamine, tähelepanu juhtimine dialoogipartneri seisukohtades esinevatele vasturääkivustele, mis võimaldab liikumist vastastikku kujuneva arusaamise suunas. Dialoogilise kommunikatsiooni lõpptulemus kujuneb mitmesuguseid perspektiive, maailmavaateid ning erinevaid sotsiaalseid rõhuasetusi arvestavalt ja lõimivalt. Avatud tähendusloome tingimuste järgimine võimaldab kommunikatsioonis osalejatel kujundada mõistlikke eelistusi ja otsustusi.

Sotsiaalmeedia avalikus ruumis aitab avatud tähendusloomet toetada suhtlusgruppidele teatud piirangute seadmine, näiteks dialoogipõhimõtteid austava kodukorra loomine, arutelude modereerimine ning isikutuvastuse nõude kehtestamine. Viimane aitab vältida olukordi, kus valeidentiteete (nt trollid või käpiknukud) luues teatud seisukohtade (eba)populaarsust kunstlikult võimendatakse, et auditooriumi manipuleerida.

Modereerimine seostub peamiselt ebasobivate kirjutiste eemaldamise, grupiga liitumissoovide rahuldamise või tagasilükkamisega, aga ka arutelu fookuse hoidmisega. Eesti puhul on modereerimise ja sotsiaalmeedia arutelude kvaliteedi seoseid võrdlemisi vähe uuritud. Poolavaliku Facebooki grupi modereerimisele keskendunud analüüs ([Orgse 2018](#Orgse2018)) tõi ühe probleemina välja, et moderaatoritel on oma väljakujunenud väärtushinnangute tõttu ideaalse dialoogi tingimusi sageli raske luua, näiteks anda sõna neile, kelle seisukoht nende omast otsustavalt erineb. Suure liikmeskonnaga gruppides on aga kõigi kasutajate arvamusavaldusi, avameelsust ja kriitikat keerulisem tagada.

### Kokkuvõte {-.chapter4_section}

Pöörasime artiklis tähelepanu sellistele tähendusloome tunnustele, mille domineerimine soodustab sotsiaalmeediaarutelude polariseerimist ja takistab argumenteeritud diskussiooni arenemist ja eri ühiskonnagruppide lõimimist. Üht või teist suhtlemisviisi ei saa iseenesest kahjulikuks pidada, näiteks võib antiteetiline tähenduseloome tõsiste ühiskondlike kriiside ajal toimida tõhusa mobiliseerijana, niisamuti on sotsiaalsete sidemete kinnitamine oluline peaaegu igas suhtlusolukorras. Problemaatiliseks muutuvad need siis, kui osutatud tähendusloome tunnused hakkavad mingis suhtluskeskkonnas domineerima viisil, mis varjutab teistsuguste arvamuste sõnastamist, pärsib suhtlejate otsustusprotsesside kriitilist analüüsi ja kasvatab manipuleerimisohtu.

Sotsiaalmeedia suhtlusoskuste parendamist võib otseselt seostada Eesti elanikkonna psühholoogilise kaitsestrateegia kujundamisega. Liberaaldemokraatlikes ühiskondades saab vaenulik infotegevus end sõnavabaduse sildi all õigustada. Erinevalt professionaalsetest ajakirjandusväljaannetest ei laiene sotsiaalmeedia vahendajatele eetika- ja kvaliteedipõhimõtted, mis rõhutavad faktikontrolli, allikapõhisust, ekspertide seisukohtade esitamist, kajastuste neutraalsuse ja vaadete tasakaalustatuse norme. Seetõttu saab vaenulikule õõnestustegevusele omast „infoudu“ loomist, strateegiliste narratiivide levitamist iseäranis edukalt ellu viia kohati kontrollimatus sotsiaalmeediakeskkonnas ([Nissen 2015, lk 11](#Nissen2015#)).

Osutatud vaenuliku infotegevuse tagajärgede vältimiseks ja sotsiaalmeedia arutelude üldise kvaliteedi tõstmiseks tuleks edendada meediaharidust, mis õpetaks tänapäevase infost üleküllastunud veebisuhtluse kriitilise analüüsimise oskust. Meediaõpetus peaks hõlmama kõiki haridusastmeid ja pöörama tähelepanu järgmistele küsimustele: kuidas avada sotsiaalmeedia tekstitüüpide (nt meemide) tähendusi ning mõista nende kasutamise eesmärke konkreetsetes aruteludes; kuidas olla sotsiaalmeediasuhtluses allikakriitiline ja märgata tekstide vahendajate võimalikke varjatud kavatsusi, kuidas tunda ära tähendusloomet, mille eesmärk on tähelepanu saavutamine, auditooriumi eksitamine ning konfliktide õhutamine.

Digitaalses avalikus ruumis toimuvate tähendusloomeprotsesside mõistmisel on oluline roll nii sotsiaal- kui ka humanitaarteadlastel. Eesti riigikaitse arengukava 2017–2026 rõhutab strateegilise kommunikatsiooni tähtsust riigikaitse arendussuunana. Selle taustal tuleks soodustada koostööd teadusasutustega, mis tegelevad sotsiaalmeedias valitsevate tähendusloomesuundumuste uurimisega. Tegemist on selgelt kultuuri- ja keelespetsiifiline uurimisvaldkonnaga ja seega ei saa teistes riikides tehtud uuringutulemusi kriitikavabalt Eestisse üle võtta. Eesti digitaalsele avalikule ruumile keskenduv akadeemiline uurimistöö vajab seega läbimõeldumat koordineerimist, millele aitaks kaasa koostöö edendamine uurimisasutuste ning inforünnakute ja meediamanipulatsioonide uurimisele keskenduvate vabatahtlike organisatsioonide (nt Propastop) vahel.

 Samuti aitab digitaalset avatud suhtlemist edendada sotsiaalmeedia platvormide suhtlusgruppide moderaatorite töökvaliteedi tõstmine näiteks moderaatoritele mõeldud koolitusprogrammide kaudu. Positiivne algatus oleks ka moderaatoritöö (riiklik) tunnustamine ning kõrgetasemeliselt modereeritud ja dialoogi soodustavate sotsiaalmeedia kommunikatsiooniruumidele kvaliteedimärkide jagamine. See eeldaks avalike sotsiaalmeedia arutelude hea tava väljatöötamist ja tutvustamist. Tunnustuse saanud keskkonnad julgustaksid erialateadlasi, asjatundjaid ja aktiivseid kodanikke sotsiaalmeedias ühiskondlikult olulistel teemadel sõna võtma. See omakorda soodustaks avatud ja argumenteeritud avalikku suhtlemist.

### Viidatud allikad {-.subreferences}

<p id="Cohen1989">Cohen, J. 1989. Deliberation and Democratic Legitimacy. – Hamlin, A., Phillip Petit, P. (eds.). The Good Polity: Normative Analysis of the State. New York: Blackwell.</p>

<p id="Habermas1998">Habermas, J. 1998. Inclusion of the Other: Studies in Political Theory. Cambridge: Polity.</p>

<p id="Howard2011">Howard, R. G. 2011. Digital Jesus: The Making of a New Christian Fundamentalist Community on the Internet. New York: New York University Press.</p>

<p id="Jantunen2018">Jantunen, S. 2018. Infosõda. Tallinn: Kultuurileht.</p>

<p id="Kaldur2017">Kaldur, K., Vetik, R., Kirss, L., Seppel, K., Kallas, K., Masso, M., Anniste, K. 2017. Eesti ühiskonna integratsiooni monitooring. Meediakasutus ja infoväli. Tallinn: Kultuuriministeerium.</p>

<p id="Kasekamp2018">Kasekamp, A., Madisson, M.-L., Wierenga, L. J. 2018. Discursive opportunities for the Estonian populist radical right in a digital society. – Problems of Post-Communism, 66 (1), 47–58.</p>

<p id="2Madisson2016">Madisson, M.-L. 2016. The Semiotic Construction of Identities in Hypermedia Environments: The Analysis of Online Communication of the Estonian Extreme Right. Tartu: University of Tartu Press.</p>

<p id="Madisson-Ventsel2016">Madisson, M.-L., Ventsel, A. 2016. Autocommunicative meaning-making in online-communication of Estonian extreme right. – Sign Systems Studies, 44 (3), 326−354.</p>

<p id="Newman2017">Newman, N., Fletcher, R., Kalogeropoulos, A., Levy, D. A. L., Nielsen, R. K. 2017. Reuters Institute Digital News Report 2017. Oxford: Reuters Institute for the Study of Journalism.</p>

<p id="Nissen2015">Nissen, T. E. 2015. Sotsiaalmeedia kasutamine relvasüsteemina. Tänapäeva konfliktide omadused. Tallinn: Tallinna Raamatutrükikoda.</p>

<p id="Opermann2018">Opermann, S. 2018. Youth news media use in Estonia. – Andersson, Y., Dalquist, U., Ohlsson, J. (eds.). Youth and News in a Digital Media Environment. Nordic-Baltic Perspectives. Göteborg: Nordicom, University of Gothenburg, 91–104.</p>

<p id="Orgse2018">Orgse, S. 2018. Facebooki arutelude modereerimine „Virginia Woolf sind ei karda!“ grupi näitel. Bakalaureusetöö. Tartu Ülikool. </p>

<p id="Papacharissi2016">Papacharissi, Z. 2016. Affective publics and structures of storytelling: sentiment, events and mediality. – Information, Communication & Society, 19 (3), 307–324.</p>

<p id="Siibak2018">Siibak, A., Masso, A. 2018. „People who defend their homeland“: motivations for joining and being active in an anti-immigration group on Facebook. – Proceedings of the 9th International Conference on Social Media and Society (SMSociety). Copenhagen: SMSociety.</p>

<p id="2Tiidenberg2017">Tiidenberg, K. 2017. Ihu ja hingega internetis. Tallinn: Tallinna Ülikooli Kirjastus.</p>

<p id="Vihalemm2017">Vihalemm, P., Kõuts-Klemm, R. 2017. Meediakasutuse muutumine: internetiajastu saabumine. – Vihalemm, P., Lauristin, M., Kalmus, V., Vihalemm, T., Keller, M. (toim.). Eesti ühiskond kiirenevas ajas: Eesti elaviku muutumine 2002–2014 uuringu „Mina. Maailm. Meedia“ tulemuste põhjal. Tartu: Tartu Ülikooli Kirjastus, 251–278.</p>
