## Ühe tunni Eesti {.chapter_section .chapter5_section}
Rahvastik linnades: 80%
Varanduslik kihistumine: väike
Ruumiline ebavõrdsus: väike
Hea avalik ruum: jagatud ja ligipääs tagatud
Andmed: igaühe omad, õigused on kaitstud
Ühiskonna kulutused baastaristule: suured, aga võrdsemalt jagatud
Sotsiaal-majanduslik efektiivsus: keskmisest suurem
Säästva arengu eesmärgid: oleme maailmas eeskujuks
 
Põhjaliku regionaalse planeerimise tulemusena on terves Eestis elamuarendus ja liikuvusteenused omavahel seotud, mistõttu on esmajärgus ehitatud rongiühendusega kohtadesse. Arendajatele tundus see alguses liiga piirav, aga inimesed on rahul ega igatse sõltuvust isiklikust sõidukist. Igal linnaregioonil on oma nägu ja keskused, mis töötavad ringmajanduse põhimõttel. Uue ärkamise on läbi teinud kunagine murelaps Ida-Virumaa, mis on esmalt kunstnike ja seejärel idusektori sinna kolimise tulemusena nüüd Eesti atraktiivsemaid ja kosmopoliitsemaid elupiirkondi, kus on teine kodu nii Peterburi, Eesti kui ka teiste maade loovinimestel. Eestimaalastele meeldib aega veeta parkides ja linnaväljakutel, kuhu nad liiguvad parajasti sobivaima liiklusvahendiga – trammiga, isejuhtiva kapsliga, vesinikrattaga või kõiki neid kombineerides. Linnades on elamuslik tänava- ja katkematu rohevõrgustik, mis aitab kliimakriisiga kohaneda, ning avalikus ruumis toimub palju möödujate tähelepanu paeluvaid tegevusi. Rakendatud on nn 8-80-põhimõte, mis tähendab, et nii 8- kui ka 80-aastased saavad avalikus ruumis kõrvalise abita liikuda. Räägitakse palju vaimse tervise hoidmisest ja ollakse tähelepanelikud, kui lähedasel inimesel võivad rasked ajad olla. Inimesed on kogukondlikult pühendunud mõnele varem avalikule võimule kuulunud tööle: aidatakse kõige nooremaid ja kõige vanemaid, rajatakse ühisaedu, kujundatakse tänavaid ja hoove. Suuremates linnades läheb uussisserändajatel sisseelamine üsna ladusalt, ehkki väiksemates kohtades võidakse neile ikka viltu vaadata. Õnneindeksis on Eesti suhteliselt eesotsas ja viimased paar aastat isegi tõusnud.
