## Krattide ja Marakrattide Eesti {.chapter_section .chapter5_section}

Rahvastik linnades: 70%
Varanduslik kihistumine: suur
Ruumiline ebavõrdsus: väga suur
Hea avalik ruum: privilegeeritud, jagatud või olematu, vastavalt kohaliku omavalitsuse võimetele
Andmed: koondunud suurte ettevõtete kätte, aga suur küberkuritegevus
Ühiskonna kulutused baastaristule: suured ja ebavõrdselt jaotatud
Sotsiaal-majanduslik efektiivsus: väga vähene
Säästva arengu eesmärgid: mõni väiksem omavalitsus on suutnud täita, tervikuna pilt kehv

Eestis on erinevad suured ja väiksemad keskused, millest võimekamad püüavad leida oma nägu – kes püüab tähelepanu kõrgtehnoloogilisi lahendusi pakkudes, kes meelitab enda juurde aina rohkem vanemaid inimesi, kes tegeleb digiteeritud agrotootmisega. Samal ajal on ka üpris mahajäänud kante, kus peamine tööandja on pankrotti läinud ja abi pole kuskilt näha. Seal jäävad silma vaid suurettevõtetele kuuluvad tuulikud ja päikesepaneelid, aga neid käitavad spetsialistid ei ole kohaliku rahva seast. Uussisserändajad on jagunenud üle terve riigi ja just väiksemates kohtades leidub neid rohkem – seal on rohkem pakkumist väga väikse palgaga töödele, mida kohalikud ise taha või ei jaksa teha – samal ajal vajavad aina vananevad asulad eriti just sotsiaaltöötaja abi. Eriti halb lugu on sõltuvushaiguste ja HIVga, mida peetakse igaühe oma veaks. Paljud varakamad inimesed elavad hajali, sest kliimakriis on isu linnades elada kustutanud: armastatakse öelda, et õige eestlane elab ikka oma aia ja põllulapiga majas. Kogukondlikku lähenemist harrastavad „hipid“, nii-öelda korralik inimene üritab aga ikka naabrist parem olla. Tänu hajusale asustusele pole avaliku ruumi kvaliteet suurem asi, pigem eelistatakse raha maanteedesse panna. Need on erineva kvaliteediga, kunagiste ambitsioonikate taristuprojektide ebaõnnestumisest on õpitud, et pole mõtet liiga suurelt üritadagi. Isejuhtivate autode ja transpordidroonide pakkujaid on erinevaid, nii et peenemale rahvale on saadaval hea teenus, vaesem rahvas aga vaatab, kuidas saab – päris tihti saab vastu näppe. Õnneindeksis on Eesti keskpärane järelelohiseja.
